# Generated by Django 3.2.3 on 2022-06-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urgentalerts',
            options={'managed': False, 'verbose_name': 'Urgent Alert', 'verbose_name_plural': 'Urgent Alerts'},
        ),
    ]
