version: "3"

services:
  db:
    image: circleci/postgres:10-postgis
    environment:
      POSTGRES_USER: defaultuser
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: testpassword

  dev:
    build:
      context: .
      dockerfile: ./compose/docker/Dockerfile-dev
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py loaddata support/fixtures/*.yaml
      && python manage.py loaddata priority_monitoring/fixtures/*.yaml
      && python manage.py loaddata funai/fixtures/funai_cr_fixtures2.yaml
      && python manage.py loaddata funai/fixtures/funai_ti_fixtures.yaml
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/home/app/
    ports:
      - "8000:8000"
    # network_mode: "host"
    environment:
      DB_USER: defaultuser
      DB_NAME: testdb
      DB_PASSWORD: testpassword
      DB_HOST: db
    depends_on:
      - db
