version: "3"

services:
  db:
    image: circleci/postgres:10-postgis
    environment:
      POSTGRES_USER: defaultuser
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: testpassword

  dev:
    build:
      context: .
      dockerfile: ./compose/docker/Dockerfile-dev
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py loaddata support/fixtures/*.yaml
      && python manage.py loaddata priority_monitoring/fixtures/priority_nonitoring_old.yaml
      && python manage.py runserver 0.0.0.0:8000"''
    volumes:
      - .:/home/app/
    ports:
      - "8000:8000"
    # network_mode: "host"
    environment:
      #DJANGO_SETTINGS_MODULE: skyviewer_api.settings.local
      DB_USER: defaultuser
      DB_NAME: testdb
      DB_PASSWORD: testpassword
      DB_HOST: db
      #DB_USER: postgres
      #DB_NAME: cmr2_desenv
      #DB_PASSWORD: 123456
      #DB_HOST: localhost
      DB_CATALOG_USER: defaultuser
      DB_CATALOG_NAME: skynetviz
      DB_CATALOG_PASSWORD: testpassword
      DB_CATALOG_HOST: db_catalog
      ALLOWED_HOSTS: '["*"]'
      SKYNETVIZ_URL: http://localhost:8001/process/catalog
      SKYNETVIZ_TOKEN: Token secret
      ELASTICSEARCH_URL: http://es:9200
    depends_on:
      - db
