version: "3"

services:
  db:
    image: circleci/postgres:10-postgis
    environment:
      POSTGRES_USER: defaultuser
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: testpassword

  db_catalog:
    image: circleci/postgres:10-postgis
    environment:
      POSTGRES_USER: defaultuser
      POSTGRES_DB: skynetviz
      POSTGRES_PASSWORD: testpassword

  prod:
    image: gcr.io/custom-plating-209314/skyviewer-api:latest
    build:
      context: .
      dockerfile: ./compose/docker/Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./compose/docker/envfile.env

  test:
    build:
      context: .
      dockerfile: ./compose/docker/Dockerfile-dev
    command: bash -c "export
      && python manage.py migrate
      && python manage.py test --no-input"
    volumes:
      - .:/home/app/
    environment:
      DJANGO_SETTINGS_MODULE: skyviewer_api.settings.local
      DB_USER: defaultuser
      DB_NAME: testdb
      DB_PASSWORD: testpassword
      DB_HOST: db
      ALLOWED_HOSTS: '["*"]'
    depends_on:
      - db

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    logging:
      driver: none
    environment:
      - discovery.type=single-node
      - "http.cors.allow-origin=*"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - db

  dev:
    build:
      context: .
      dockerfile: ./compose/docker/Dockerfile-dev
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py loaddata support/fixtures/*.yaml
      python manage.py loaddata priority_monitoring/fixtures/*.yaml
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/home/app/
    ports:
      - "8000:8000"
    # network_mode: "host"
    environment:
      #DJANGO_SETTINGS_MODULE: skyviewer_api.settings.local
      DB_USER: defaultuser
      DB_NAME: testdb
      DB_PASSWORD: testpassword
      DB_HOST: db
      #DB_USER: postgres
      #DB_NAME: cmr2_desenv
      #DB_PASSWORD: 123456
      #DB_HOST: localhost
      DB_CATALOG_USER: defaultuser
      DB_CATALOG_NAME: skynetviz
      DB_CATALOG_PASSWORD: testpassword
      DB_CATALOG_HOST: db_catalog
      ALLOWED_HOSTS: '["*"]'
      SKYNETVIZ_URL: http://localhost:8001/process/catalog
      SKYNETVIZ_TOKEN: Token secret
      ELASTICSEARCH_URL: http://es:9200
    depends_on:
      - db
