# Generated by Django 3.2.3 on 2025-01-09 11:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('components', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('layers', 'Camadas de Sobreposição'), ('monitoring', 'Monitoramento Diário'), ('layers_mosaics', 'Alta Resolução e Mosaicos'), ('layers_planet', 'Camadas Planet'), ('land_use', 'Uso e Ocupação do Solo'), ('analytics', 'Módulo Analítico'), ('admin_panel', 'Painel Administrativo')], max_length=20), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='LayerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('layers', models.ManyToManyField(blank=True, related_name='layer_permissions', to='layer.Layer')),
            ],
        ),
    ]
