# Generated by Django 3.2.3 on 2025-03-25 16:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentpermission',
            name='components',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('layers', 'Camadas de Sobreposição'), ('monitoring', 'Monitoramento Diário'), ('layers_mosaics', 'Alta Resolução e Mosaicos'), ('layers_planet', 'Camadas Planet'), ('land_use', 'Uso e Ocupação do Solo'), ('analytics', 'Módulo Analítico'), ('admin_panel', 'Painel Administrativo'), ('feedback_dev', 'Críticas e Sugestões Dev'), ('feedback_admin', 'Críticas e Sugestões ADM')], max_length=20), blank=True, size=None),
        ),
    ]
