# Generated by Django 3.2.3 on 2025-01-14 22:23

import admin_panel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('solicitation_type', models.CharField(blank=True, choices=[('ERRO', 'Erro'), ('MELHORIA', 'Melhoria'), ('NOVA_FUNCIONALIDADE', 'Nova Funcionalidade'), ('OUTROS', 'Outros')], default='ERRO', max_length=20, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('opened_in', models.DateTimeField(auto_now_add=True)),
                ('complexity_code', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (5, '5'), (8, '8'), (13, '13'), (21, '21')], default=1, null=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'admin_panel_tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed_update', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=500)),
                ('sub_status', models.CharField(blank=True, choices=[('AGUARDANDO_GESTOR', 'Aguardando Gestor'), ('EM_DESENVOLVIMENTO', 'Em Desenvolvimento'), ('CONCLUIDO', 'Concluído'), ('EM_TESTE', 'Em Teste'), ('INVIAVEL', 'Inviável'), ('INDEFERIDO', 'Indeferido'), ('DEFERIDO', 'Deferido'), ('NAO_ANALISADO', 'Não Analisado')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Ticket Analysis History',
                'verbose_name_plural': 'Tickets Analysis History',
                'db_table': 'admin_panel_tickets_analysis_history',
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to=admin_panel.models.rename_file_ticket)),
                ('name_file', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ticket Attachment',
                'verbose_name_plural': 'Tickets Attachments',
                'db_table': 'admin_panel_tickets_attachment',
            },
        ),
        migrations.CreateModel(
            name='TicketFunctionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ticket Functionality',
                'verbose_name_plural': 'Tickets Functionalities',
                'db_table': 'admin_panel_tickets_funcionality',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_category', models.CharField(blank=True, choices=[('NAO_ANALISADO', 'Não Analisado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('RECUSADO', 'Recusado'), ('DEFERIDO', 'Deferido')], default='NAO_ANALISADO', max_length=20, null=True)),
                ('sub_status', models.CharField(blank=True, choices=[('AGUARDANDO_GESTOR', 'Aguardando Gestor'), ('EM_DESENVOLVIMENTO', 'Em Desenvolvimento'), ('CONCLUIDO', 'Concluído'), ('EM_TESTE', 'Em Teste'), ('INVIAVEL', 'Inviável'), ('INDEFERIDO', 'Indeferido'), ('DEFERIDO', 'Deferido'), ('NAO_ANALISADO', 'Não Analisado')], default='NAO_ANALISADO', max_length=20, null=True)),
                ('priority_code', models.CharField(blank=True, choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='BAIXA', max_length=20, null=True)),
                ('analyzed_in', models.DateTimeField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ticket Status',
                'verbose_name_plural': 'Tickets Status',
                'db_table': 'admin_panel_tickets_status',
            },
        ),
        migrations.CreateModel(
            name='TicketStatusAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to=admin_panel.models.rename_file_ticket_status)),
                ('name_file', models.CharField(max_length=100)),
                ('ticket_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history_attachments', to='admin_panel.ticketanalysishistory')),
                ('ticket_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_attachments', to='admin_panel.ticketstatus')),
            ],
            options={
                'verbose_name': 'Ticket Status Attachment',
                'verbose_name_plural': 'Tickets Status Attachments',
                'db_table': 'admin_panel_tickets_status_attachments',
            },
        ),
    ]
