# Generated by Django 3.2.3 on 2025-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketanalysishistory',
            name='sub_status',
            field=models.CharField(blank=True, choices=[('AGUARDANDO_GESTOR', 'Aguardando Gestor'), ('EM_DESENVOLVIMENTO', 'Em Desenvolvimento'), ('CONCLUIDO', 'Concluído'), ('EM_TESTE', 'Em Teste'), ('DESENVOLVIDO', 'Desenvolvido'), ('INVIAVEL', 'Inviável'), ('INDEFERIDO', 'Indeferido'), ('DEFERIDO', 'Deferido'), ('NAO_ANALISADO', 'Não Analisado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='sub_status',
            field=models.CharField(blank=True, choices=[('AGUARDANDO_GESTOR', 'Aguardando Gestor'), ('EM_DESENVOLVIMENTO', 'Em Desenvolvimento'), ('CONCLUIDO', 'Concluído'), ('EM_TESTE', 'Em Teste'), ('DESENVOLVIDO', 'Desenvolvido'), ('INVIAVEL', 'Inviável'), ('INDEFERIDO', 'Indeferido'), ('DEFERIDO', 'Deferido'), ('NAO_ANALISADO', 'Não Analisado')], default='NAO_ANALISADO', max_length=20, null=True),
        ),
    ]
