# Generated by Django 3.2.3 on 2025-05-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20250505_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketanalysishistory',
            name='sub_status',
            field=models.CharField(blank=True, choices=[('AGUARDANDO_GESTOR', 'Aguardando Gestor'), ('EM_DESENVOLVIMENTO', 'Em Desenvolvimento'), ('CONCLUIDO', 'Concluído'), ('EM_TESTE', 'Em Teste'), ('INVIAVEL', 'Inviável'), ('INDEFERIDO', 'Indeferido'), ('DEFERIDO', 'Deferido'), ('DESENVOLVIDO', 'Desenvolvido'), ('NAO_ANALISADO', 'Não Analisado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='status_category',
            field=models.CharField(blank=True, choices=[('NAO_ANALISADO', 'Não Analisado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('RECUSADO', 'Recusado'), ('DEFERIDO', 'Deferido'), ('DESENVOLVIDO', 'Desenvolvido')], default='NAO_ANALISADO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='sub_status',
            field=models.CharField(blank=True, choices=[('AGUARDANDO_GESTOR', 'Aguardando Gestor'), ('EM_DESENVOLVIMENTO', 'Em Desenvolvimento'), ('CONCLUIDO', 'Concluído'), ('EM_TESTE', 'Em Teste'), ('INVIAVEL', 'Inviável'), ('INDEFERIDO', 'Indeferido'), ('DEFERIDO', 'Deferido'), ('DESENVOLVIDO', 'Desenvolvido'), ('NAO_ANALISADO', 'Não Analisado')], default='NAO_ANALISADO', max_length=20, null=True),
        ),
    ]
