# Generated by Django 3.2.3 on 2025-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20250506_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(help_text='Description of the ticket', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ticketanalysishistory',
            name='comment',
            field=models.TextField(help_text='Comment about the ticket analysis', verbose_name='Comentário'),
        ),
    ]
