# Generated by Django 3.2.3 on 2025-06-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20250623_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketanalysishistory',
            name='sub_status',
        ),
        migrations.RemoveField(
            model_name='ticketstatus',
            name='sub_status',
        ),
        migrations.AddField(
            model_name='ticketanalysishistory',
            name='status_category',
            field=models.CharField(blank=True, choices=[('NAO_ANALISADO', 'Não Analisado'), ('INDEFERIDO', 'Indeferido'), ('DEFERIDO', 'Deferido'), ('AGUARDANDO_GESTOR', 'Aguardando Gestor'), ('EM_DESENVOLVIMENTO', 'Em Desenvolvimento'), ('DESENVOLVIDO', 'Desenvolvido'), ('CONCLUIDO', 'Concluído'), ('RECUSADO', 'Recusado')], help_text='Status category at the time of analysis', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='status_category',
            field=models.CharField(blank=True, choices=[('NAO_ANALISADO', 'Não Analisado'), ('INDEFERIDO', 'Indeferido'), ('DEFERIDO', 'Deferido'), ('AGUARDANDO_GESTOR', 'Aguardando Gestor'), ('EM_DESENVOLVIMENTO', 'Em Desenvolvimento'), ('DESENVOLVIDO', 'Desenvolvido'), ('CONCLUIDO', 'Concluído'), ('RECUSADO', 'Recusado')], default='NAO_ANALISADO', max_length=20, null=True),
        ),
    ]
