# Generated by Django 3.2.3 on 2025-06-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20250623_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketanalysishistory',
            name='sub_status',
        ),
        migrations.RemoveField(
            model_name='ticketstatus',
            name='sub_status',
        ),
    ]
