# Generated by Django 3.2.3 on 2025-06-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_auto_20250625_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketanalysishistory',
            name='status_category',
            field=models.CharField(blank=True, choices=[('NAO_ANALISADO', 'Não Analisado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('RECUSADO', 'Recusado'), ('DEFERIDO', 'Deferido'), ('DESENVOLVIDO', 'Desenvolvido')], help_text='Status category at the time of analysis', max_length=20, null=True),
        ),
    ]
