# Generated by Django 3.2.3 on 2025-07-04 17:45

import admin_panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_auto_20250626_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file_path',
            field=models.FileField(upload_to=admin_panel.models.rename_file_ticket, validators=[admin_panel.models.validate_file_size, admin_panel.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='ticketstatusattachment',
            name='file_path',
            field=models.FileField(upload_to=admin_panel.models.rename_file_ticket_status, validators=[admin_panel.models.validate_file_size, admin_panel.models.validate_file_extension]),
        ),
    ]
