# Generated by Django 3.2.3 on 2025-06-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_ticketanalysishistory_status_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketanalysishistory',
            name='status_category',
            field=models.CharField(blank=True, choices=[('NAO_ANALISADO', 'Não Analisado'), ('AGUARDANDO_GESTOR', 'Aguardando Gestor'), ('EM_DESENVOLVIMENTO', 'Em Desenvolvimento'), ('CONCLUIDO', 'Concluído'), ('RECUSADO', 'Recusado'), ('DEFERIDO', 'Deferido'), ('DESENVOLVIDO', 'Desenvolvido')], help_text='Status category at the time of analysis', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='status_category',
            field=models.CharField(blank=True, choices=[('NAO_ANALISADO', 'Não Analisado'), ('AGUARDANDO_GESTOR', 'Aguardando Gestor'), ('EM_DESENVOLVIMENTO', 'Em Desenvolvimento'), ('CONCLUIDO', 'Concluído'), ('RECUSADO', 'Recusado'), ('DEFERIDO', 'Deferido'), ('DESENVOLVIDO', 'Desenvolvido')], default='NAO_ANALISADO', max_length=20, null=True),
        ),
    ]
