# Generated by Django 3.2.3 on 2024-08-01 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date_login', models.DateTimeField(verbose_name='Data Último Login')),
                ('location', models.CharField(max_length=255, verbose_name='Localização')),
                ('ip', models.CharField(max_length=255, verbose_name='IP')),
                ('type_device', models.CharField(max_length=255)),
                ('browser', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Data',
                'ordering': ('-last_date_login',),
            },
        ),
    ]
