# Generated by Django 3.2.3 on 2025-02-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date_login', models.DateTimeField(verbose_name='Data Último Login')),
                ('location', models.CharField(max_length=255, verbose_name='Localização')),
                ('ip', models.CharField(max_length=255, verbose_name='IP')),
                ('type_device', models.CharField(max_length=255)),
                ('browser', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dashboard Data',
                'ordering': ('-last_date_login',),
            },
        ),
    ]
