# Generated by Django 3.2.3 on 2024-07-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='browser',
            field=models.CharField(default='teste', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='type_device',
            field=models.CharField(default='teste', max_length=255),
            preserve_default=False,
        ),
    ]
