# Generated by Django 3.2.3 on 2024-08-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
