# Generated by Django 3.2.3 on 2024-08-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLayersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True, unique=True, verbose_name='Name')),
                ('icon', models.CharField(blank=True, default='layers', max_length=255, null=True, verbose_name='Icon')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category Groups Layers',
                'verbose_name_plural': 'Categories Groups Layers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Geoserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('wms_url', models.CharField(max_length=500, verbose_name='Wms URL')),
                ('preview_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Preview URL')),
            ],
            options={
                'verbose_name': 'Geoserver',
                'verbose_name_plural': 'Geoservers',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
                ('layer_type', models.CharField(max_length=40, verbose_name='Layer Type')),
                ('active_on_init', models.BooleanField(default=False, verbose_name='Active on Init')),
                ('is_public', models.BooleanField(default=False, verbose_name='Geoservice is Public')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='TmsLayer',
            fields=[
                ('url_tms', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL TMS')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('max_native_zoom', models.IntegerField(blank=True, null=True, verbose_name='Max Native Zoom')),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='tms', serialize=False, to='support.layer')),
            ],
            options={
                'verbose_name': 'TMS Layer',
                'verbose_name_plural': 'TMS Layers',
            },
        ),
        migrations.CreateModel(
            name='LayersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(blank=True, max_length=255, verbose_name='Fonte')),
                ('dt_atualizacao', models.DateField(blank=True, null=True, verbose_name='Atualização')),
                ('database_layer_name', models.CharField(max_length=255, verbose_name='Database Layer Name')),
                ('layer_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='layer_info', to='support.layer')),
            ],
            options={
                'verbose_name': 'Layer Info',
                'verbose_name_plural': 'Layers Info',
            },
        ),
        migrations.CreateModel(
            name='LayersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('order', models.IntegerField(unique=True, verbose_name='Order')),
                ('category_groups', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='support.categorylayersgroup')),
            ],
            options={
                'verbose_name': 'Layers Group',
                'verbose_name_plural': 'Layers Groups',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='LayerFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.CharField(blank=True, max_length=40, null=True, verbose_name='Default value for filters')),
                ('filter_type', models.CharField(max_length=40, verbose_name='Filter Type')),
                ('label', models.CharField(max_length=40, verbose_name='Filter Label')),
                ('filter_alias', models.CharField(max_length=40, verbose_name='Filter WMS services')),
                ('layers', models.ManyToManyField(related_name='layer_filters', to='support.Layer')),
            ],
            options={
                'verbose_name': 'Layer Filter',
                'verbose_name_plural': 'Layer Filters',
            },
        ),
        migrations.AddField(
            model_name='layer',
            name='layers_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='layers', to='support.layersgroup'),
        ),
        migrations.CreateModel(
            name='WmsLayer',
            fields=[
                ('has_preview', models.BooleanField(default=True, verbose_name='Has preview')),
                ('has_detail', models.BooleanField(default=False, verbose_name='Has detail')),
                ('detail_width', models.IntegerField(blank=True, null=True, verbose_name='Detail width')),
                ('geoserver_layer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Geoserver Layer Name')),
                ('geoserver_layer_namespace', models.CharField(blank=True, max_length=40, null=True, verbose_name='Geoserver Layer Namespace')),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='wms', serialize=False, to='support.layer')),
                ('geoserver_layer_options', models.JSONField(blank=True, null=True, verbose_name='Geoserver Layer Options')),
                ('queryable', models.BooleanField(default=True, verbose_name='WmsLayer is queryable')),
                ('has_opacity', models.BooleanField(default=True, verbose_name='Has opacity')),
                ('default_opacity', models.IntegerField(blank=True, null=True, verbose_name='Default opacity')),
                ('geoserver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='layers', to='support.geoserver')),
            ],
            options={
                'verbose_name': 'WMS Layer',
                'verbose_name_plural': 'WMS Layers',
            },
        ),
    ]
