# Generated by Django 3.2.3 on 2021-12-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geoserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('wms_url', models.CharField(max_length=500)),
                ('preview_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Geoserver',
                'verbose_name_plural': 'Geoservers',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
                ('layer_type', models.CharField(max_length=40, verbose_name='Layer Type')),
                ('active_on_init', models.BooleanField(default=False, verbose_name='Active on Init')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='LayersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('order', models.IntegerField(unique=True, verbose_name='Order')),
                ('icon', models.CharField(blank=True, default='layers', max_length=255, null=True, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Layers Group',
                'verbose_name_plural': 'Layers Groups',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='TmsLayer',
            fields=[
                ('url_tms', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('max_native_zoom', models.IntegerField(blank=True, null=True, verbose_name='Max Native Zoom')),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='tms', serialize=False, to='support.layer')),
            ],
            options={
                'verbose_name': 'TmsLayer',
                'verbose_name_plural': 'TmsLayers',
            },
        ),
        migrations.AddField(
            model_name='layer',
            name='layers_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='layers', to='support.layersgroup'),
        ),
        migrations.CreateModel(
            name='WmsLayer',
            fields=[
                ('has_preview', models.BooleanField(default=True)),
                ('has_detail', models.BooleanField(default=False)),
                ('detail_width', models.IntegerField(blank=True, null=True)),
                ('geoserver_layer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Geoserver Layer Name')),
                ('geoserver_layer_namespace', models.CharField(blank=True, max_length=40, null=True, verbose_name='Geoserver Layer Namespace')),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='wms', serialize=False, to='support.layer')),
                ('geoserver_layer_options', models.JSONField(blank=True, null=True, verbose_name='Geoserver Layer Options')),
                ('queryable', models.BooleanField(default=True)),
                ('has_opacity', models.BooleanField(default=True)),
                ('default_opacity', models.IntegerField(blank=True, null=True)),
                ('geoserver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='layers', to='support.geoserver')),
            ],
            options={
                'verbose_name': 'WmsLayer',
                'verbose_name_plural': 'WmsLayers',
            },
        ),
    ]
