# Generated by Django 3.2.3 on 2021-12-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geoserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('wms_url', models.CharField(max_length=500)),
                ('preview_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Geoserver',
                'verbose_name_plural': 'Geoservers',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
                ('layer_type', models.CharField(max_length=40, verbose_name='Layer Type')),
                ('active_on_init', models.BooleanField(default=False, verbose_name='Active on Init')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
                'ordering': ['-order'],
            },
        ),
    ]
