# Generated by Django 3.2.3 on 2021-12-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('order', models.IntegerField(unique=True, verbose_name='Order')),
                ('icon', models.CharField(blank=True, default='layers', max_length=255, null=True, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Layers Group',
                'verbose_name_plural': 'Layers Groups',
                'ordering': ['-order'],
            },
        ),
    ]
