# Generated by Django 3.2.3 on 2022-05-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20220324_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorylayersgroup',
            options={'ordering': ['name'], 'verbose_name': 'Category Groups Layers', 'verbose_name_plural': 'Categories Groups Layers'},
        ),
    ]
