# Generated by Django 3.2.3 on 2022-05-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_categorylayersgroup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.CharField(blank=True, max_length=40, null=True, verbose_name='Default value for filters')),
                ('filter_type', models.CharField(max_length=40, verbose_name='Filter Type')),
                ('label', models.CharField(max_length=40, verbose_name='Filter Label')),
                ('filter_alias', models.CharField(max_length=40, verbose_name='Filter WMS services')),
                ('layers', models.ManyToManyField(related_name='layer_filters', to='support.Layer')),
            ],
            options={
                'verbose_name': 'LayerFilter',
                'verbose_name_plural': 'LayerFilters',
            },
        ),
    ]
