# Generated by Django 3.2.3 on 2023-08-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_layerfilter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layerfilter',
            options={'verbose_name': 'Layer Filter', 'verbose_name_plural': 'Layer Filters'},
        ),
        migrations.AlterModelOptions(
            name='tmslayer',
            options={'verbose_name': 'TMS Layer', 'verbose_name_plural': 'TMS Layers'},
        ),
        migrations.AlterModelOptions(
            name='wmslayer',
            options={'verbose_name': 'WMS Layer', 'verbose_name_plural': 'WMS Layers'},
        ),
        migrations.AddField(
            model_name='layer',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Geoservice is Public'),
        ),
        migrations.AlterField(
            model_name='categorylayersgroup',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='categorylayersgroup',
            name='name',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='geoserver',
            name='preview_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Preview URL'),
        ),
        migrations.AlterField(
            model_name='geoserver',
            name='wms_url',
            field=models.CharField(max_length=500, verbose_name='Wms URL'),
        ),
        migrations.AlterField(
            model_name='tmslayer',
            name='url_tms',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL TMS'),
        ),
        migrations.AlterField(
            model_name='wmslayer',
            name='default_opacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Default opacity'),
        ),
        migrations.AlterField(
            model_name='wmslayer',
            name='detail_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Detail width'),
        ),
        migrations.AlterField(
            model_name='wmslayer',
            name='has_detail',
            field=models.BooleanField(default=False, verbose_name='Has detail'),
        ),
        migrations.AlterField(
            model_name='wmslayer',
            name='has_opacity',
            field=models.BooleanField(default=True, verbose_name='Has opacity'),
        ),
        migrations.AlterField(
            model_name='wmslayer',
            name='has_preview',
            field=models.BooleanField(default=True, verbose_name='Has preview'),
        ),
        migrations.AlterField(
            model_name='wmslayer',
            name='queryable',
            field=models.BooleanField(default=True, verbose_name='WmsLayer is queryable'),
        ),
    ]
