# Generated by Django 3.2.3 on 2024-06-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20230809_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(blank=True, max_length=255, verbose_name='Fonte')),
                ('dt_atualizacao', models.DateField(blank=True, null=True, verbose_name='Atualização')),
                ('database_layer_name', models.CharField(max_length=255, verbose_name='Database Layer Name')),
                ('layer_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='layer_info', to='support.layer')),
            ],
            options={
                'verbose_name': 'Layer Info',
                'verbose_name_plural': 'Layers Info',
            },
        ),
    ]
