# Generated by Django 3.2.3 on 2024-03-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20230809_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=255, verbose_name='Fonte')),
                ('layer_id', models.IntegerField(unique=True, verbose_name='Layer_id')),
                ('dt_atualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Atualização')),
                ('database_layer_name', models.CharField(max_length=255, verbose_name='Database Layer Name')),
            ],
            options={
                'verbose_name': 'Layer Info',
                'verbose_name_plural': 'Layers Info',
            },
        ),
    ]
