# Generated by Django 3.2.3 on 2024-04-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_layersinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layersinfo',
            name='dt_atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='layersinfo',
            name='fonte',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='layersinfo',
            name='layer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='layer_info', to='support.layer'),
        ),
    ]
