# Generated by Django 3.2.3 on 2024-06-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_auto_20240422_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terraindigena',
            name='co_cr',
        ),
        migrations.DeleteModel(
            name='CoordenacaoRegional',
        ),
        migrations.DeleteModel(
            name='TerraIndigena',
        ),
    ]
