# Generated by Django 3.2.3 on 2024-06-06 19:29

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_auto_20240606_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenacaoRegional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_cr', models.BigIntegerField(default=1, unique=True, verbose_name='Regional Coordenation code')),
                ('ds_email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('ds_telefone', models.TextField(blank=True, null=True, verbose_name='Contact number')),
                ('dt_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Register date')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4674)),
                ('no_abreviado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Regional Coordenation acronym')),
                ('no_cr', models.CharField(max_length=100)),
                ('no_municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='City name')),
                ('no_regiao', models.CharField(blank=True, max_length=12, null=True, verbose_name='Region name')),
                ('no_uf', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('sg_cr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Regional Coordenation flag')),
                ('sg_uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='State acronym')),
                ('st_situacao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Situation')),
            ],
            options={
                'verbose_name': 'Regional Coordinations',
                'verbose_name_plural': 'Regional Coordinations',
                'ordering': ['no_cr'],
            },
        ),
        migrations.CreateModel(
            name='TerraIndigena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4674)),
                ('no_ti', models.CharField(max_length=255, verbose_name='Name of Indigenous Lands')),
                ('co_funai', models.IntegerField(unique=True, verbose_name='Funai code')),
                ('no_grupo_etnico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo Étnico')),
                ('ds_fase_ti', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fase TI')),
                ('ds_modalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidade TI')),
                ('ds_reestudo_ti', models.CharField(blank=True, max_length=80, null=True, verbose_name='Reestudo TI')),
                ('ds_cr', models.CharField(blank=True, max_length=100, null=True)),
                ('no_municipio', models.TextField(blank=True, null=True)),
                ('sg_uf', models.CharField(blank=True, max_length=20, null=True)),
                ('st_faixa_fronteira', models.CharField(blank=True, max_length=3, null=True)),
                ('dt_em_estudo', models.DateField(blank=True, null=True)),
                ('ds_portaria_em_estudo', models.TextField(blank=True, null=True)),
                ('dt_delimitada', models.DateField(blank=True, null=True)),
                ('ds_despacho_delimitada', models.TextField(blank=True, null=True)),
                ('dt_declarada', models.DateField(blank=True, null=True)),
                ('ds_portaria_declarada', models.TextField(blank=True, null=True)),
                ('dt_homologada', models.DateField(blank=True, null=True)),
                ('ds_decreto_homologada', models.TextField(blank=True, null=True)),
                ('dt_regularizada', models.DateField(blank=True, null=True)),
                ('ds_matricula_regularizada', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_em_estudo', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_delimitada', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_declarada', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_homologada', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_regularizada', models.TextField(blank=True, null=True)),
                ('st_amazonia_legal', models.BooleanField(blank=True, null=True)),
                ('nu_area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True)),
                ('co_cr', models.ForeignKey(db_column='co_cr', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='terras_indigenas', to='support.coordenacaoregional', to_field='co_cr')),
            ],
            options={
                'verbose_name': 'Indigenous Lands',
                'verbose_name_plural': 'Indigenous Lands',
                'ordering': ['no_ti'],
            },
        ),
    ]
