# Generated by Django 3.2.3 on 2024-06-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_coordenacaoregional_terraindigena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terraindigena',
            name='co_cr',
        ),
        migrations.DeleteModel(
            name='CoordenacaoRegional',
        ),
        migrations.DeleteModel(
            name='TerraIndigena',
        ),
    ]
