# Generated by Django 3.2.3 on 2025-02-12 21:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandUseClasses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='primary key')),
                ('sg_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brazilian states flag')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Indigenous Lands')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Funai code for Indigenous Land')),
                ('dt_homologada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of ratification of Indigenous Lands')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordination name')),
                ('co_cr', models.BigIntegerField(blank=True, null=True, verbose_name='Regional Coordination code')),
                ('nu_ano', models.IntegerField(blank=True, null=True, verbose_name='Reference mapping year')),
                ('no_estagio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stage name land use mapping')),
                ('no_satelites', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellites used in mapping')),
                ('nu_resolucoes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellite spatial resolution')),
                ('dt_imagens', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mapped image date')),
                ('nu_area_km2', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area polygon km2')),
                ('nu_area_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area polygon ha')),
                ('dt_cadastro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Registration date')),
                ('nu_latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Latitude')),
                ('nu_longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Longitude')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Geometry Field')),
            ],
            options={
                'verbose_name': 'Land Use Mapping Class',
                'verbose_name_plural': 'Land Use Mapping Classes',
                'db_table': 'funaidados"."img_analise_consolidado_oneatlas_dissolvido_por_estagio_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandUsePerTi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='primary key')),
                ('sg_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brazilian states flag')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Indigenous Lands')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Funai code for Indigenous Land')),
                ('co_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordination code')),
                ('dt_homologada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of ratification of Indigenous Lands')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordination name')),
                ('nu_ano', models.IntegerField(blank=True, null=True, verbose_name='Reference mapping year')),
                ('no_satelites', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Satelites Data')),
                ('nu_resolucoes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Number of Resolutions')),
                ('dt_imagens', models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of Images')),
                ('nu_area_ag_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='agriculture')),
                ('nu_area_cr_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='clear cutting')),
                ('nu_area_dg_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Degradation')),
                ('nu_area_ma_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Water Body')),
                ('nu_area_no_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Not Observed')),
                ('nu_area_rv_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Highway')),
                ('nu_area_sv_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Forestry')),
                ('nu_area_vi_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Village')),
                ('nu_area_vn_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Natural Vegetation')),
                ('nu_area_mi_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Mining')),
                ('nu_area_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='area')),
                ('nu_area_km2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='area in kilometers')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Geometry Field')),
                ('nu_latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Latitude')),
                ('nu_longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Land Use Mapping Per TI',
                'verbose_name_plural': 'Land Use Mapping Per TIs',
                'db_table': 'funaidados"."img_analise_consolidado_oneatlas_dissolvido_por_ti_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandUseVmRegionalCoordnation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='primary key')),
                ('cr_co_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Code of Regional Coordination')),
                ('cr_no_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Regional Coordination')),
                ('cr_no_regiao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regiona Name of Regional Coordination')),
                ('ti_co_funai', models.CharField(blank=True, max_length=255, null=True, verbose_name='funai code of Indigenous Land')),
                ('ti_no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Indigenous Land')),
            ],
            options={
                'verbose_name': 'Land Use Mapping Regional Coordination',
                'verbose_name_plural': 'Land Use Mapping Regional Coordinations',
                'db_table': 'funai"."vwm_painel_coordenacao_regional_terra_indigena',
                'managed': False,
            },
        ),
    ]
