# Generated by Django 3.2.3 on 2024-08-01 13:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandUseClasses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='primary key')),
                ('sg_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brazilian states flag')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Indigenous Lands')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Funai code for Indigenous Land')),
                ('dt_homologada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of ratification of Indigenous Lands')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordination name')),
                ('co_cr', models.BigIntegerField(blank=True, null=True, verbose_name='Regional Coordination code')),
                ('nu_ano', models.IntegerField(blank=True, null=True, verbose_name='Reference mapping year')),
                ('no_estagio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stage name land use mapping')),
                ('no_satelites', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellites used in mapping')),
                ('nu_resolucoes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellite spatial resolution')),
                ('dt_imagens', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mapped image date')),
                ('nu_area_km2', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area polygon km2')),
                ('nu_area_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area polygon ha')),
                ('dt_cadastro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Registration date')),
                ('nu_latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Latitude')),
                ('nu_longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Longitude')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Geometry Field')),
            ],
            options={
                'verbose_name': 'Land Use Mapping Class',
                'verbose_name_plural': 'Land Use Mapping Classes',
                'db_table': 'funaidados"."img_analise_consolidado_oneatlas_dissolvido_por_estagio_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandUseTI',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='primary key')),
                ('sg_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brazilian states flag')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Indigenous Lands')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Funai code for Indigenous Lands')),
                ('dt_homologada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of ratification of Indigenous Lands')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordination name')),
                ('co_cr', models.BigIntegerField(blank=True, null=True, verbose_name='Regional Coordination code')),
                ('nu_ano', models.IntegerField(blank=True, null=True, verbose_name='Reference mapping year')),
                ('no_satelites', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellites used in mapping')),
                ('nu_resolucoes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellite spatial resolution')),
                ('dt_imagens', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mapped image date')),
                ('nu_area_ag_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area agricultural polygon ha')),
                ('nu_area_cr_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area clear cut polygon ha')),
                ('nu_area_dg_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area degradation polygon ha')),
                ('nu_area_ma_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area body of water polygon ha')),
                ('nu_area_no_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area not observed polygon ha')),
                ('nu_area_rv_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area highway polygon ha')),
                ('nu_area_sv_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area forestry polygon ha')),
                ('nu_area_vi_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area village polygon ha')),
                ('nu_area_vn_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area natural vegetation polygon ha')),
                ('nu_area_mi_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area mining polygon ha')),
                ('nu_area_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area polygon ha')),
                ('nu_area_km2', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area polygon km2')),
                ('nu_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Latitude')),
                ('nu_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Longitude')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Geometry Field')),
            ],
            options={
                'verbose_name': 'Land Use Mapping TI',
                'verbose_name_plural': 'Land Use Mapping TIs',
                'db_table': 'funaidados"."img_analise_consolidado_oneatlas_dissolvido_por_ti_a',
                'managed': False,
            },
        ),
    ]
