# Generated by Django 3.2.3 on 2022-05-05 21:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_use', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUseClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='')),
                ('no_ti', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('dt_homologada', models.CharField(blank=True, max_length=10, null=True, verbose_name='')),
                ('ds_cr', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('nu_ano', models.CharField(blank=True, max_length=4, null=True, verbose_name='')),
                ('no_estagio', models.CharField(blank=True, max_length=2, null=True, verbose_name='')),
                ('no_satelites', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('nu_resolucoes', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('dt_imagens', models.CharField(blank=True, max_length=10, null=True, verbose_name='')),
                ('nu_area_ha', models.FloatField(blank=True, null=True, verbose_name='')),
                ('dt_cadastro', models.DateField(blank=True, null=True, verbose_name='Date of')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Geometry Field')),
            ],
            options={
                'verbose_name': 'Land Use Mapping Class',
                'verbose_name_plural': 'Land Use Mapping Classes',
            },
        ),
        migrations.CreateModel(
            name='LandUseTI',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='primary key')),
                ('sg_uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='')),
                ('no_ti', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('dt_homologada', models.CharField(blank=True, max_length=10, null=True, verbose_name='')),
                ('ds_cr', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('nu_ano', models.CharField(blank=True, max_length=4, null=True, verbose_name='')),
                ('no_satelites', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('nu_resolucoes', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('dt_imagens', models.CharField(blank=True, max_length=10, null=True, verbose_name='')),
                ('nu_area_ag_ha', models.FloatField(blank=True, null=True, verbose_name='')),
                ('nu_area_cr_ha', models.FloatField(blank=True, null=True, verbose_name='')),
                ('nu_area_dg_ha', models.FloatField(blank=True, null=True, verbose_name='')),
                ('nu_area_ma_ha', models.FloatField(blank=True, null=True, verbose_name='')),
                ('nu_area_no_ha', models.FloatField(blank=True, null=True, verbose_name='')),
                ('nu_area_rv_ha', models.FloatField(blank=True, null=True, verbose_name='')),
                ('nu_area_sv_ha', models.FloatField(blank=True, null=True, verbose_name='')),
                ('nu_area_vi_ha', models.FloatField(blank=True, null=True, verbose_name='')),
                ('nu_area_vn_ha', models.FloatField(blank=True, null=True, verbose_name='')),
                ('nu_area_mi_ha', models.FloatField(blank=True, null=True, verbose_name='')),
                ('nu_area_ha', models.FloatField(blank=True, null=True, verbose_name='')),
                ('nu_area_km2', models.FloatField(blank=True, null=True, verbose_name='')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Geometry Field')),
            ],
            options={
                'verbose_name': 'Land Use Mapping TI',
                'verbose_name_plural': 'Land Use Mapping TIs',
            },
        ),
        migrations.DeleteModel(
            name='LandUseMappingClasses',
        ),
        migrations.DeleteModel(
            name='LandUseMappingTI',
        ),
    ]
