# Generated by Django 3.2.3 on 2022-05-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_use', '0002_auto_20220505_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuseclasses',
            name='co_cr',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Regional Coordination code'),
        ),
        migrations.AddField(
            model_name='landuseclasses',
            name='nu_area_km2',
            field=models.FloatField(blank=True, null=True, verbose_name='Area polygon km2'),
        ),
        migrations.AddField(
            model_name='landuseclasses',
            name='nu_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='landuseclasses',
            name='nu_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='landuseti',
            name='co_cr',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Regional Coordination code'),
        ),
        migrations.AddField(
            model_name='landuseti',
            name='nu_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='landuseti',
            name='nu_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='landuseclasses',
            name='co_funai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Funai code for Indigenous Land'),
        ),
        migrations.AlterField(
            model_name='landuseclasses',
            name='ds_cr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordination name'),
        ),
        migrations.AlterField(
            model_name='landuseclasses',
            name='dt_cadastro',
            field=models.DateField(blank=True, null=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='landuseclasses',
            name='dt_homologada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of ratification of Indigenous Lands'),
        ),
        migrations.AlterField(
            model_name='landuseclasses',
            name='dt_imagens',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mapped image date'),
        ),
        migrations.AlterField(
            model_name='landuseclasses',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='primary key'),
        ),
        migrations.AlterField(
            model_name='landuseclasses',
            name='no_estagio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stage name land use mapping'),
        ),
        migrations.AlterField(
            model_name='landuseclasses',
            name='no_satelites',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellites used in mapping'),
        ),
        migrations.AlterField(
            model_name='landuseclasses',
            name='no_ti',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Indigenous Lands'),
        ),
        migrations.AlterField(
            model_name='landuseclasses',
            name='nu_ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reference mapping year'),
        ),
        migrations.AlterField(
            model_name='landuseclasses',
            name='nu_area_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area polygon ha'),
        ),
        migrations.AlterField(
            model_name='landuseclasses',
            name='nu_resolucoes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellite spatial resolution'),
        ),
        migrations.AlterField(
            model_name='landuseclasses',
            name='sg_uf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brazilian states flag'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='co_funai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Funai code for Indigenous Lands'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='ds_cr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordination name'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='dt_homologada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of ratification of Indigenous Lands'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='dt_imagens',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mapped image date'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='no_satelites',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellites used in mapping'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='no_ti',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Indigenous Lands'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reference mapping year'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_area_ag_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area agricultural polygon ha'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_area_cr_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area clear cut polygon ha'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_area_dg_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area degradation polygon ha'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_area_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area polygon ha'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_area_km2',
            field=models.FloatField(blank=True, null=True, verbose_name='Area polygon km2'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_area_ma_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area body of water polygon ha'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_area_mi_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area mining polygon ha'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_area_no_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area not observed polygon ha'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_area_rv_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area highway polygon ha'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_area_sv_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area forestry polygon ha'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_area_vi_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area village polygon ha'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_area_vn_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area natural vegetation polygon ha'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='nu_resolucoes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellite spatial resolution'),
        ),
        migrations.AlterField(
            model_name='landuseti',
            name='sg_uf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brazilian states flag'),
        ),
    ]
