# Generated by Django 3.2.3 on 2022-05-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_use', '0003_auto_20220517_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landuseclasses',
            options={'managed': False, 'verbose_name': 'Land Use Mapping Class', 'verbose_name_plural': 'Land Use Mapping Classes'},
        ),
        migrations.AlterModelOptions(
            name='landuseti',
            options={'managed': False, 'verbose_name': 'Land Use Mapping TI', 'verbose_name_plural': 'Land Use Mapping TIs'},
        ),
    ]
