# Generated by Django 3.2.3 on 2022-05-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_use', '0004_auto_20220518_2007'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='landuseclasses',
            table='funaidados"."img_analise_consolidado_oneatlas_dissolvido_por_estagio_a',
        ),
        migrations.AlterModelTable(
            name='landuseti',
            table='funaidados"."img_analise_consolidado_oneatlas_dissolvido_por_ti_a',
        ),
    ]
