from django.urls import path
from .views import GroupUserListView, RoleUserListView, RoleUserDiffView, GroupPermissionListView, RoleGroupDiffView, LayerPermissionListView, ComponentPermissionListView, LayerPermissionView, LayerPermissionDiffView

urlpatterns = [
    path(
        '',
        LayerPermissionListView.as_view(),
        name='permissions'
    ),
    path(
        'layer/',
        LayerPermissionView.as_view(),
        name='layer-permissions'
    ),
    path(
        'role/',
        GroupPermissionListView.as_view(),
        name='layer-permissions'
    ),
    path(
        'layer/<int:pk>/',
        LayerPermissionView.as_view(),
        name='layer-permission-detail'
    ),
    path(
        'layer-diff/<int:pk>/',
        LayerPermissionDiffView.as_view(),
        name='layer-permission-diff'
    ),
    path(
        'role/<int:pk>/users/',
        RoleUserListView.as_view(),
        name='role-users-list'
    ),
    path(
        'role/<int:pk>/users-diff/',
        RoleUserDiffView.as_view(),
        name='role-users-difference'
    ),
    path(
        'role-diff/<int:pk>/',
        RoleGroupDiffView.as_view(),
        name='layer-permission-diff'
    ),
    path(
        'component/',
        ComponentPermissionListView.as_view(),
        name='component-permissions'
    ),
    path(
        'group/<int:pk>/users/',
        GroupUserListView.as_view(),
        name='group-users-list'
    ),
]
