# Generated by Django 3.2.3 on 2025-06-13 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the change was made')),
                ('action', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], help_text='Whether the role was added or removed', max_length=20)),
                ('changed_by', models.ForeignKey(help_text='Administrator who made the change', on_delete=django.db.models.deletion.CASCADE, related_name='role_changes_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='The role that was added or removed', on_delete=django.db.models.deletion.CASCADE, to='user.role')),
                ('user', models.ForeignKey(help_text='User whose roles were modified', on_delete=django.db.models.deletion.CASCADE, related_name='role_changes_affected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Change',
                'verbose_name_plural': 'User Role Changes',
                'db_table': 'history_user_role_changes',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the change occurred')),
                ('old_username', models.CharField(help_text='Previous username', max_length=255, null=True)),
                ('new_username', models.CharField(help_text='New username', max_length=255, null=True)),
                ('old_email', models.EmailField(help_text='Previous email address', max_length=254, null=True)),
                ('new_email', models.EmailField(help_text='New email address', max_length=254, null=True)),
                ('old_institution', models.CharField(help_text='Previous institution name', max_length=255, null=True)),
                ('new_institution', models.CharField(help_text='New institution name', max_length=255, null=True)),
                ('old_is_active', models.BooleanField(help_text='Previous active status', null=True)),
                ('new_is_active', models.BooleanField(help_text='New active status', null=True)),
                ('changed_by', models.ForeignKey(help_text='Administrator who made the change', on_delete=django.db.models.deletion.CASCADE, related_name='changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User whose data was modified', on_delete=django.db.models.deletion.CASCADE, related_name='changes_affected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Change History',
                'verbose_name_plural': 'User Change Histories',
                'db_table': 'history_user_changes',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userrolechange',
            index=models.Index(fields=['user', '-changed_at'], name='history_use_user_id_d4e2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='userrolechange',
            index=models.Index(fields=['role', '-changed_at'], name='history_use_role_id_5f3430_idx'),
        ),
        migrations.AddIndex(
            model_name='userchangehistory',
            index=models.Index(fields=['user', '-changed_at'], name='history_use_user_id_5cec77_idx'),
        ),
        migrations.AddIndex(
            model_name='userchangehistory',
            index=models.Index(fields=['changed_by', '-changed_at'], name='history_use_changed_7075e8_idx'),
        ),
    ]
