# Generated by Django 3.2.3 on 2025-06-12 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_username', models.CharField(max_length=255, null=True)),
                ('new_username', models.CharField(max_length=255, null=True)),
                ('old_email', models.EmailField(max_length=254, null=True)),
                ('new_email', models.EmailField(max_length=254, null=True)),
                ('old_institution', models.CharField(max_length=255, null=True)),
                ('new_institution', models.CharField(max_length=255, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_affected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
