# Generated by Django 3.2.3 on 2025-04-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_funai', models.IntegerField(verbose_name='Cod Funai')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Terras Indígena')),
                ('no_regiao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Região')),
                ('sg_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='UF')),
                ('no_povo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Povos')),
                ('no_bioma', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bioma')),
                ('ds_parceiros', models.CharField(blank=True, max_length=255, null=True, verbose_name='Parceiros')),
                ('cr_funai', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Funai')),
                ('no_ig', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instrumento')),
                ('ds_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status')),
                ('nu_ano_elaboracao', models.IntegerField(blank=True, null=True, verbose_name='Elaborado em')),
                ('ds_disp_meio_local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Disponível em')),
                ('ds_tll_publi', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('ds_obs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('dt_cadastro', models.DateField(blank=True, null=True, verbose_name='Data Registro')),
            ],
            options={
                'verbose_name': 'Management Instrument',
                'verbose_name_plural': 'Management Instruments',
            },
        ),
    ]
