# Generated by Django 3.2.3 on 2025-04-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0002_managementinstrument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagementInstrument',
        ),
    ]
