# Generated by Django 3.2.3 on 2025-04-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0003_delete_managementinstrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='is_update_daily',
            field=models.BooleanField(default=False, help_text='Enable layer update daily', verbose_name='Atualização diária'),
        ),
    ]
