# Generated by Django 3.2.3 on 2022-08-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sattelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40, unique=True, verbose_name='Identifier')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name sattelite')),
                ('description', models.TextField(blank=True, max_length=511, null=True, verbose_name='Description')),
            ],
        ),
    ]
