# Generated by Django 3.2.3 on 2024-08-01 13:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False, verbose_name='Object id')),
                ('image', models.CharField(max_length=255, unique=True, verbose_name='Product scene')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('image_path', models.CharField(help_text='This link is used to download the processed scene.', max_length=511, verbose_name='Image repository')),
                ('url_tms', models.CharField(help_text='This link contains the scena TMS service file.', max_length=511, verbose_name='Tile file link')),
                ('date', models.DateField(verbose_name='Scene Date')),
                ('pr_date', models.DateField(verbose_name='Process Date')),
                ('cloud_cover', models.FloatField(default=0, null=True, verbose_name='Percentage of cloud cover')),
                ('locator', models.CharField(max_length=255, null=True, verbose_name='Satellite scene parameters')),
                ('max_native_zoom', models.IntegerField(default=15, verbose_name='Maximum zoom scale')),
                ('sat_identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellite identifier')),
                ('sat_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellite name')),
                ('preview', models.TextField(blank=True, help_text='This link contains the scena preview thumb file.', max_length=511, null=True, verbose_name='Image preveiw link')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Geometry Field')),
            ],
            options={
                'verbose_name': 'Satellite Scene',
                'verbose_name_plural': 'Satellite Scenes',
                'db_table': 'catalogo"."vw_new_img_catalogo_a',
                'ordering': ('-date',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='Identifier')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellite name')),
                ('description', models.TextField(blank=True, max_length=511, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Satellite',
                'verbose_name_plural': 'Satellites',
                'ordering': ('name',),
            },
        ),
    ]
