# Generated by Django 3.2.3 on 2022-10-14 13:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landsat8Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255, unique=True, verbose_name='Color composition name')),
                ('product', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product scene')),
                ('type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Composition type')),
                ('date', models.DateField(verbose_name='Scene Date')),
                ('cloud_cover', models.FloatField(null=True, verbose_name='Percentage of cloud cover')),
                ('url_tms', models.CharField(max_length=511, verbose_name='Tile path')),
                ('path', models.CharField(max_length=511, verbose_name='Image repository')),
                ('download_link', models.CharField(max_length=511, verbose_name='Image repository')),
                ('download_available', models.BooleanField(default=False, verbose_name='Download allowed')),
                ('max_native_zoom', models.IntegerField(default=15, verbose_name='Maximum zoom scale')),
                ('co_cr', models.BigIntegerField(verbose_name='Regional Coordenation code')),
                ('ds_cr', models.CharField(max_length=255, verbose_name='Regional Coordenation name')),
                ('co_funai', models.IntegerField(verbose_name='Funai code')),
                ('no_ti', models.CharField(max_length=255, verbose_name='Name of Indigenous Lands')),
                ('municipio', models.CharField(blank=True, max_length=255, null=True, verbose_name='County')),
                ('sg_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='State aconymn')),
                ('resolution', models.IntegerField(blank=True, null=True, verbose_name='Spatial resolution')),
                ('nu_latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero latitude')),
                ('nu_longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero longitude')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4674, verbose_name='Geometry Field')),
                ('orbita', models.CharField(blank=True, max_length=3, null=True, verbose_name='Satellite Path')),
                ('ponto', models.CharField(blank=True, max_length=3, null=True, verbose_name='Satellite Row')),
            ],
            options={
                'verbose_name': 'Landsat8 Catalog',
                'verbose_name_plural': 'Landsat8 Catalogs',
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40, unique=True, verbose_name='Identifier')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellite name')),
                ('description', models.TextField(blank=True, max_length=511, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Satellite',
                'verbose_name_plural': 'Satellites',
            },
        ),
        migrations.CreateModel(
            name='Sentinel2Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255, unique=True, verbose_name='Color composition name')),
                ('product', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product scene')),
                ('type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Composition type')),
                ('date', models.DateField(verbose_name='Scene Date')),
                ('cloud_cover', models.FloatField(null=True, verbose_name='Percentage of cloud cover')),
                ('url_tms', models.CharField(max_length=511, verbose_name='Tile path')),
                ('path', models.CharField(max_length=511, verbose_name='Image repository')),
                ('download_link', models.CharField(max_length=511, verbose_name='Image repository')),
                ('download_available', models.BooleanField(default=False, verbose_name='Download allowed')),
                ('max_native_zoom', models.IntegerField(default=15, verbose_name='Maximum zoom scale')),
                ('co_cr', models.BigIntegerField(verbose_name='Regional Coordenation code')),
                ('ds_cr', models.CharField(max_length=255, verbose_name='Regional Coordenation name')),
                ('co_funai', models.IntegerField(verbose_name='Funai code')),
                ('no_ti', models.CharField(max_length=255, verbose_name='Name of Indigenous Lands')),
                ('municipio', models.CharField(blank=True, max_length=255, null=True, verbose_name='County')),
                ('sg_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='State aconymn')),
                ('resolution', models.IntegerField(blank=True, null=True, verbose_name='Spatial resolution')),
                ('nu_latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero latitude')),
                ('nu_longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero longitude')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4674, verbose_name='Geometry Field')),
                ('utm_zone', models.IntegerField(blank=True, null=True, verbose_name='UTM Zone')),
                ('latitude_band', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude Band')),
                ('grid_square', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grid Square')),
                ('satellite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.satellite')),
            ],
            options={
                'verbose_name': 'Sentinel2 Catalog',
                'verbose_name_plural': 'Sentinel2 Catalogs',
            },
        ),
        migrations.DeleteModel(
            name='Sattelite',
        ),
        migrations.AddField(
            model_name='landsat8catalog',
            name='satellite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.satellite'),
        ),
    ]
