# Generated by Django 3.2.3 on 2023-01-17 13:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20221014_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogs',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False, verbose_name='Object id')),
                ('image', models.CharField(max_length=255, unique=True, verbose_name='Product scene')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('image_path', models.CharField(max_length=511, verbose_name='Image repository')),
                ('url_tms', models.CharField(max_length=511, verbose_name='Tile file link')),
                ('date', models.DateTimeField(verbose_name='Scene Date')),
                ('pr_date', models.DateField(auto_now_add=True, verbose_name='Process Date')),
                ('cloud_cover', models.FloatField(default=0, null=True, verbose_name='Percentage of cloud cover')),
                ('locator', models.CharField(max_length=255, null=True, verbose_name='Satellite scene parameters')),
                ('max_native_zoom', models.IntegerField(default=15, verbose_name='Maximum zoom scale')),
                ('sat', models.IntegerField(blank=True, null=True, verbose_name='Satellite identifier')),
                ('sat_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellite name')),
                ('preview', models.TextField(blank=True, max_length=511, null=True, verbose_name='Image preveiw link')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4674, verbose_name='Geometry Field')),
            ],
            options={
                'verbose_name': 'Catalog Scene',
                'verbose_name_plural': 'Catalogs Scenes',
                'ordering': ('-date',),
            },
        ),
        migrations.RemoveField(
            model_name='sentinel2catalog',
            name='satellite',
        ),
        migrations.AlterModelOptions(
            name='satellite',
            options={'ordering': ('name',), 'verbose_name': 'Satellite', 'verbose_name_plural': 'Satellites'},
        ),
        migrations.AlterField(
            model_name='satellite',
            name='identifier',
            field=models.CharField(max_length=255, unique=True, verbose_name='Identifier'),
        ),
        migrations.DeleteModel(
            name='Landsat8Catalog',
        ),
        migrations.DeleteModel(
            name='Sentinel2Catalog',
        ),
    ]
