# Generated by Django 3.2.3 on 2023-01-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20230117_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogs',
            options={'managed': False, 'ordering': ('-date',), 'verbose_name': 'Catalog Scene', 'verbose_name_plural': 'Catalogs Scenes'},
        ),
    ]
