# Generated by Django 3.2.3 on 2021-12-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityConsolidated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_estagio', models.CharField(blank=True, max_length=255, null=True)),
                ('no_cr', models.CharField(blank=True, max_length=255, null=True)),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('prioridade', models.CharField(blank=True, choices=[('A', 'Alta'), ('M', 'Média'), ('B', 'Baixa')], default='B', max_length=1, null=True)),
                ('flag', models.BooleanField(blank=True, default=False, null=True)),
                ('dt_t_um', models.DateField(blank=True, null=True)),
                ('geom', models.CharField(blank=True, default='000', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriorityConsolidatedTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb_ciclo_monitoramento_id', models.CharField(blank=True, max_length=255, null=True)),
                ('no_estagio', models.CharField(blank=True, max_length=255, null=True)),
                ('no_imagem', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_imagem', models.DateField(blank=True, null=True)),
                ('nu_orbita', models.CharField(blank=True, max_length=255, null=True)),
                ('nu_ponto', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_t_zero', models.DateField(blank=True, null=True)),
                ('dt_t_um', models.DateField(blank=True, null=True)),
                ('nu_area_km2', models.CharField(blank=True, max_length=255, null=True)),
                ('nu_area_ha', models.CharField(blank=True, max_length=255, null=True)),
                ('nu_latitude', models.CharField(blank=True, max_length=512, null=True)),
                ('nu_longitude', models.CharField(blank=True, max_length=512, null=True)),
                ('tempo', models.IntegerField(blank=True, null=True)),
                ('contribuicao', models.CharField(blank=True, max_length=255, null=True)),
                ('velocidade', models.CharField(blank=True, max_length=255, null=True)),
                ('contiguidade', models.IntegerField(blank=True, null=True)),
                ('ranking', models.CharField(blank=True, max_length=255, null=True)),
                ('prioridade', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_cadastro', models.DateField(blank=True, null=True)),
                ('co_uf', models.IntegerField(blank=True, null=True)),
                ('co_municipio', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
