# Generated by Django 3.2.3 on 2022-01-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priority_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priorityconsolidatedtb',
            old_name='dt_imagem',
            new_name='dt_image',
        ),
        migrations.RenameField(
            model_name='priorityconsolidatedtb',
            old_name='dt_t_um',
            new_name='dt_t0',
        ),
        migrations.RenameField(
            model_name='priorityconsolidatedtb',
            old_name='dt_t_zero',
            new_name='dt_t1',
        ),
        migrations.RenameField(
            model_name='priorityconsolidatedtb',
            old_name='co_municipio',
            new_name='id_tb',
        ),
        migrations.RenameField(
            model_name='priorityconsolidatedtb',
            old_name='no_imagem',
            new_name='no_image',
        ),
        migrations.RemoveField(
            model_name='priorityconsolidatedtb',
            name='co_uf',
        ),
        migrations.AddField(
            model_name='priorityconsolidatedtb',
            name='geom',
            field=models.JSONField(blank=True, null=True, verbose_name='Priority Consolidated Geometry'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='contribuicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='dt_cadastro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='nu_area_ha',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='nu_area_km2',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='nu_latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='nu_longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='ranking',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='tb_ciclo_monitoramento_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='velocidade',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
    ]
