# Generated by Django 3.2.3 on 2022-01-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priority_monitoring', '0002_auto_20220103_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='nu_area_ha',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='nu_area_km2',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='nu_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='nu_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='ranking',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidatedtb',
            name='velocidade',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
