# Generated by Django 3.2.3 on 2022-01-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priority_monitoring', '0003_auto_20220103_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityConsolidatedTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_estagio', models.CharField(blank=True, max_length=255, null=True)),
                ('no_cr', models.CharField(blank=True, max_length=255, null=True)),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('prioridade', models.CharField(blank=True, choices=[('A', 'Alta'), ('M', 'Média'), ('B', 'Baixa')], default='B', max_length=1, null=True)),
                ('flag', models.BooleanField(default=False)),
                ('dt_t_um', models.DateField(blank=True, null=True)),
                ('geom', models.CharField(blank=True, default='000', max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PriorityConsolidatedTb',
        ),
        migrations.RenameField(
            model_name='priorityconsolidated',
            old_name='dt_t_um',
            new_name='dt_image',
        ),
        migrations.RenameField(
            model_name='priorityconsolidated',
            old_name='no_cr',
            new_name='no_image',
        ),
        migrations.RenameField(
            model_name='priorityconsolidated',
            old_name='no_ti',
            new_name='nu_orbita',
        ),
        migrations.RemoveField(
            model_name='priorityconsolidated',
            name='flag',
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='contiguidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='contribuicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='dt_cadastro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='dt_t0',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='dt_t1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='id_tb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='nu_area_ha',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='nu_area_km2',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='nu_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='nu_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='nu_ponto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='tb_ciclo_monitoramento_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='tempo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='velocidade',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='geom',
            field=models.JSONField(blank=True, null=True, verbose_name='Priority Consolidated Geometry'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='prioridade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='ranking',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
