# Generated by Django 3.2.3 on 2022-01-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priority_monitoring', '0004_auto_20220111_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriorityConsolidatedTemp',
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='contiguidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contiguity'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='contribuicao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contribution'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='dt_cadastro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Register Date'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='dt_image',
            field=models.DateField(blank=True, null=True, verbose_name='Image date'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='dt_t0',
            field=models.DateField(blank=True, null=True, verbose_name='Date of first detected change'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='dt_t1',
            field=models.DateField(blank=True, null=True, verbose_name='Date of changes hadn"t began'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='id_tb',
            field=models.IntegerField(blank=True, null=True, verbose_name='Table identifier'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='no_estagio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stage name'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='no_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image identifier'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='nu_area_ha',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Area ha'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='nu_area_km2',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Area km'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='nu_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='nu_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='nu_orbita',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Path number'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='nu_ponto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Row number'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='prioridade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='ranking',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='tb_ciclo_monitoramento_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Monitoring cycle identifier'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='tempo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='priorityconsolidated',
            name='velocidade',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Speed'),
        ),
    ]
