# Generated by Django 3.2.3 on 2022-01-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priority_monitoring', '0005_auto_20220111_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorityconsolidated',
            name='no_cr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordination name'),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='no_ti',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indigenou Lands name'),
        ),
    ]
