# Generated by Django 3.2.3 on 2022-01-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priority_monitoring', '0007_priorityconsolidated_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorityconsolidated',
            name='co_cr',
            field=models.BigIntegerField(blank=True, default=1, null=True, verbose_name='Regional Coordenation code'),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='co_funai',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Funai code - Indigenou Lands'),
        ),
    ]
