# Generated by Django 3.2.3 on 2022-02-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority_monitoring', '0008_auto_20220113_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priorityconsolidated',
            options={'ordering': ('-dt_t0', 'ranking', 'no_estagio'), 'verbose_name': 'Priority Consolidated', 'verbose_name_plural': 'Priority Consolidated'},
        ),
    ]
