# Generated by Django 3.2.3 on 2022-03-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority_monitoring', '0009_alter_priorityconsolidated_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='priorityconsolidated',
            table='funaidados"."vwm_monitoramento_consolidado_priorizacao_a',
        ),
    ]
