# Generated by Django 3.2.3 on 2022-03-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priority_monitoring', '0010_alter_priorityconsolidated_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priorityconsolidated',
            options={'ordering': ('-dt_t_zero', 'ranking', 'no_estagio'), 'verbose_name': 'Priority Consolidated', 'verbose_name_plural': 'Priority Consolidated'},
        ),
        migrations.RemoveField(
            model_name='priorityconsolidated',
            name='dt_image',
        ),
        migrations.RemoveField(
            model_name='priorityconsolidated',
            name='dt_t0',
        ),
        migrations.RemoveField(
            model_name='priorityconsolidated',
            name='dt_t1',
        ),
        migrations.RemoveField(
            model_name='priorityconsolidated',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='priorityconsolidated',
            name='no_cr',
        ),
        migrations.RemoveField(
            model_name='priorityconsolidated',
            name='no_image',
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='ds_cr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordination name'),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='dt_imagem',
            field=models.DateField(blank=True, null=True, verbose_name='Image date'),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='dt_t_um',
            field=models.DateField(blank=True, null=True, verbose_name='Date of changes hadn"t began'),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='dt_t_zero',
            field=models.DateField(blank=True, null=True, verbose_name='Date of first detected change'),
        ),
        migrations.AddField(
            model_name='priorityconsolidated',
            name='no_imagem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image identifier'),
        ),
    ]
