# Generated by Django 3.2.3 on 2022-03-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority_monitoring', '0011_auto_20220307_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorityconsolidated',
            name='id_tb',
        ),
    ]
