# Generated by Django 3.2.3 on 2022-03-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority_monitoring', '0012_remove_priorityconsolidated_id_tb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priorityconsolidated',
            options={'managed': False, 'ordering': ('-dt_t_zero', 'ranking', 'no_estagio'), 'verbose_name': 'Priority Consolidated', 'verbose_name_plural': 'Priority Consolidated'},
        ),
    ]
