# Generated by Django 3.2.3 on 2022-05-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority_monitoring', '0014_alter_priorityconsolidated_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priorityconsolidated',
            options={'managed': False, 'ordering': ('-ranking', 'no_estagio'), 'verbose_name': 'Priority Consolidated', 'verbose_name_plural': 'Priorities Consolidated'},
        ),
    ]
