# Generated by Django 3.2.3 on 2024-04-10 19:23

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='auth.user')),
                ('drawer_open_on_init', models.BooleanField(default=True)),
                ('interest_area_zoom_on_init', models.BooleanField(default=True)),
                ('map_zoom_buttons_visible', models.BooleanField(default=True)),
                ('map_initial_area_visible', models.BooleanField(default=True)),
                ('map_zoom_to_point_visible', models.BooleanField(default=True)),
                ('map_file_loader_visible', models.BooleanField(default=True)),
                ('map_draw_button_visible', models.BooleanField(default=True)),
                ('map_opacity_button_visible', models.BooleanField(default=True)),
                ('map_reachability_button_visible', models.BooleanField(default=True)),
                ('map_my_location_visible', models.BooleanField(default=True)),
                ('map_search_button_visible', models.BooleanField(default=True)),
                ('map_scale_visible', models.BooleanField(default=True)),
                ('minimap_visible', models.BooleanField(default=True)),
                ('map_pointer_coordinates_visible', models.BooleanField(default=True)),
                ('initial_extent', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4674)),
            ],
            options={
                'verbose_name': 'UserSettings',
                'verbose_name_plural': 'UserSettings',
                'ordering': ('-user',),
            },
        ),
        migrations.CreateModel(
            name='UserUploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Uploaded File',
                'verbose_name_plural': 'User Uploaded Files',
                'ordering': ('-user',),
            },
        ),
        migrations.CreateModel(
            name='UserUploadedFileGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('user_uploaded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_uploaded_file', to='user_profile.useruploadedfile')),
            ],
            options={
                'verbose_name': 'User Uploaded File - Geometry',
                'verbose_name_plural': 'User Uploaded Files - Geometries',
                'ordering': ('user_uploaded',),
            },
        ),
    ]
