# Generated by Django 3.2.3 on 2024-07-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='dark_mode_active',
            field=models.BooleanField(default=False),
        ),
    ]
