# Generated by Django 3.2.3 on 2024-09-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20240903_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='siape_registration',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='coordinator_siape_registration',
            field=models.IntegerField(default=1518769484),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='user_siape_registration',
            field=models.IntegerField(default=484484654),
            preserve_default=False,
        ),
    ]
