# Generated by Django 3.2.3 on 2024-09-05 12:39

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20240903_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=user_profile.models.rename_file),
        ),
    ]
