# Generated by Django 3.2.3 on 2024-08-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('permission', models.CharField(blank=True, max_length=255, null=True)),
                ('permission_name', models.CharField(blank=True, max_length=255, null=True)),
                ('permission_layer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_layer', models.BooleanField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='support.layersgroup')),
                ('permission_layer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='support.layer')),
            ],
            options={
                'verbose_name': 'User permission',
                'verbose_name_plural': 'User permissions',
            },
        ),
    ]
