# Generated by Django 3.2.3 on 2024-08-12 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        ('authorization', '0002_alter_userpermissions_permission_layer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='permission_layer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='support.layer'),
        ),
    ]
