# Generated by Django 3.2.3 on 2024-08-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userpermission'),
        ('support', '0001_initial'),
        ('authorization', '0003_alter_userpermissions_permission_layer_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPermissions',
            new_name='PermissionsList',
        ),
    ]
