# Generated by Django 3.2.3 on 2024-08-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_rename_userpermissions_permissionslist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionslist',
            options={'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions List'},
        ),
    ]
