# Generated by Django 3.2.3 on 2022-03-30 20:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funai', '0014_auto_20220307_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringConsolidated',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Polygon identifier and primary key')),
                ('tb_ciclo_monitoramento_id', models.IntegerField(blank=True, null=True, verbose_name='Monitoring cycle identifier')),
                ('no_imagem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image identifier')),
                ('dt_imagem', models.DateField(blank=True, null=True, verbose_name='Image date')),
                ('no_estagio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stage name')),
                ('dt_cadastro', models.DateField(blank=True, null=True, verbose_name='Date of register polygon change')),
                ('dt_t_um', models.DateField(blank=True, null=True, verbose_name='Date of changes hadn"t began')),
                ('nu_area_km2', models.BigIntegerField(blank=True, null=True, verbose_name='Area polygon km2')),
                ('nu_area_ha', models.BigIntegerField(blank=True, null=True, verbose_name='Area polygon ha')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordination name')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indigenou Lands name')),
                ('ti_nu_area_ha', models.BigIntegerField(blank=True, null=True, verbose_name='Area Indigenou Lands ha')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Geometry Field')),
                ('co_cr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cr_monitoring', to='funai.coordenacaoregional')),
                ('co_funai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ti_monitoring', to='funai.limiteterraindigena', to_field='co_funai')),
            ],
            options={
                'verbose_name': 'Monitoramento Consolidado',
                'verbose_name_plural': 'Monitoramentos Consolidado',
                'ordering': ('-dt_t_um',),
            },
        ),
    ]
