# Generated by Django 3.2.3 on 2022-05-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_monitoringconsolidated_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringconsolidated',
            options={'managed': False, 'ordering': ('-dt_t_um',), 'verbose_name': 'Monitoring Consolidated', 'verbose_name_plural': 'Monitorings Consolidated'},
        ),
    ]
