# Generated by Django 3.2.3 on 2022-05-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_monitoringconsolidated_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monitoringconsolidated',
            table='funaidados"."img_monitoramento_terra_indigena_cr_a',
        ),
    ]
