# Generated by Django 3.2.3 on 2022-10-27 19:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_monitoringconsolidated_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringConsolidatedStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_imagem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image identifier')),
                ('dt_imagem', models.DateField(blank=True, null=True, verbose_name='Image date')),
                ('no_estagio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stage name')),
                ('dt_t_um', models.DateField(blank=True, null=True, verbose_name='Date of changes hadn"t began')),
                ('dt_cadastro', models.DateField(blank=True, null=True, verbose_name='Date of registration')),
                ('nu_area_km2', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area polygon km2')),
                ('nu_area_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area polygon ha')),
                ('no_ciclo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cycle of monitoring Indigenous Lands in the Legal Amazon')),
                ('co_cr', models.BigIntegerField(blank=True, null=True, verbose_name='Funai code')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordination name')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Funai code - Indigenou Lands')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indigenou Lands name')),
                ('ti_nu_area_ha', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area Indigenou Lands ha')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Geometry Field')),
            ],
            options={
                'verbose_name': 'Monitoring Consolidated Statistic',
                'verbose_name_plural': 'Monitorings Consolidated Statistics',
            },
        ),
    ]
