# Generated by Django 3.2.3 on 2022-11-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_monitoringconsolidatedstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonitoringConsolidatedStats',
        ),
    ]
