# Generated by Django 3.2.3 on 2025-01-10 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Concedida'), (3, 'Recusada')], default=1)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('denied_details', models.CharField(blank=True, max_length=255, null=True)),
                ('access_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.accessrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Request Status',
                'verbose_name_plural': 'Access Request Status',
            },
        ),
    ]
