# Generated by Django 3.2.3 on 2025-01-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='department',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='user.institution'),
        ),
    ]
