# Generated by Django 3.2.3 on 2025-04-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20250317_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(blank=True, help_text='Type of Institution', max_length=255, null=True),
        ),
    ]
