# Generated by Django 3.2.3 on 2025-04-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_institution_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Concedida'), (3, 'Recusada'), (4, 'Pendente Coordenador')], default=4, help_text='Current status of the access request'),
        ),
    ]
