# Generated by Django 3.2.3 on 2025-04-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_accessrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='institution_type',
        ),
    ]
