# Generated by Django 3.2.3 on 2025-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_institution_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('FUNAI Sede', 'FUNAI Sede'), ('Outros', 'Outros')], help_text='Type', max_length=128, null=True),
        ),
    ]
