# Generated by Django 3.2.3 on 2025-06-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_institution_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='acronym',
            field=models.CharField(blank=True, help_text='Acronym', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('FUNAI Sede', 'FUNAI Sede'), ('Coordenação Regional', 'Coordenação Regional'), ('Outros', 'Outros')], help_text='Type', max_length=128, null=True),
        ),
    ]
