# Generated by Django 3.2.3 on 2025-07-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20250626_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dark_mode_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
