# Generated by Django 5.1.4 on 2025-07-15 12:00

from django.db import migrations


def fix_status_values(apps, schema_editor):
    """
    Update existing AccessRequest status values to match new choices
    """
    AccessRequest = apps.get_model('user', 'AccessRequest')
    
    # Update status values to match new choices
    # Old values: (1, 'Pendente'), (2, 'Concedida'), (3, 'Recusada'), (4, 'Pendente Coordenador')
    # New values: (1, 'Pendente'), (2, 'Aprovado pelo Gestor'), (3, 'Recusada'), (4, 'Concedida')
    status_mapping = {
        1: 1,  # Pendente -> Pendente (no change)
        2: 4,  # Old "Concedida" -> New "Concedida" 
        3: 3,  # Recusada -> Recusada (no change)
        4: 2,  # Old "Pendente Coordenador" -> New "Aprovado pelo Gestor"
    }
    
    for old_status, new_status in status_mapping.items():
        AccessRequest.objects.filter(status=old_status).update(status=new_status)


def reverse_fix_status_values(apps, schema_editor):
    """
    Reverse the status value changes
    """
    AccessRequest = apps.get_model('user', 'AccessRequest')
    
    # Reverse mapping
    # New values: (1, 'Pendente'), (2, 'Aprovado pelo Gestor'), (3, 'Recusada'), (4, 'Concedida')
    # Old values: (1, 'Pendente'), (2, 'Concedida'), (3, 'Recusada'), (4, 'Pendente Coordenador')
    status_mapping = {
        1: 1,  # Pendente -> Pendente (no change)
        4: 2,  # New "Concedida" -> Old "Concedida" 
        3: 3,  # Recusada -> Recusada (no change)
        2: 4,  # New "Aprovado pelo Gestor" -> Old "Pendente Coordenador"
    }
    
    for old_status, new_status in status_mapping.items():
        AccessRequest.objects.filter(status=old_status).update(status=new_status)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_dark_mode_active'),
    ]

    operations = [
        migrations.RunPython(fix_status_values, reverse_fix_status_values),
    ]
