# Generated by Django 5.1.4 on 2025-07-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_fix_accessrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrequest',
            old_name='department',
            new_name='institution',
        ),
    ]
