# Generated by Django 3.2.3 on 2025-07-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_department_to_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='coordinator_department',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='coordinator_institution',
            field=models.CharField(blank=True, help_text='Institution of the coordinator', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='institution',
            field=models.CharField(help_text='Institution of the requester', max_length=255),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Aprovado pelo Gestor'), (3, 'Recusada'), (4, 'Concedida')], default=1, help_text='Current status of the access request'),
        ),
    ]
