"""
Django settings for cmr2_api project.

Generated by 'django-admin startproject' using Django 1.11.29.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import logging.config
import logging
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType, PosixGroupType
import ldap
import os
import datetime
from environs import Env

env = Env()
env.read_env()

# INSTANCE OF ENV VARIABLES

DEBUG = env.bool('DEBUG', default=False)
SECRET_KEY = env.str('SECRET_KEY')
GEOSERVER_URL = env.str('GEOSERVER_URL')
GEO_SEARCH_VILLAGE = env.str('GEO_SEARCH_VILLAGE')
GEO_SEARCH_STUDY_TI = env.str('GEO_SEARCH_STUDY_TI')
LDAP_PASS = env.str('LDAP_PASS')
LDAP_BASE_DN = env.str('LDAP_BASE_DN')
RESET_PASSWORD_URL = env.str('RESET_PASSWORD_URL')
DB_NAME = env.str('DB_NAME')
DB_USER = env.str('DB_USER')
DB_PASSWORD = env.str('DB_PASSWORD')
DB_HOST = env.str('DB_HOST')
DB_PORT = env.int('DB_PORT')
LDAP_URI = env.str('LDAP_URI')
DB_NAME_FOR_READ = env.str('DB_NAME_FOR_READ')
DB_USER_FOR_READ = env.str('DB_USER_FOR_READ')
DB_PASSWORD_FOR_READ = env.str('DB_PASSWORD_FOR_READ')
DB_HOST_FOR_READ = env.str('DB_HOST_FOR_READ')
DB_PORT_FOR_READ = env.int('DB_PORT_FOR_READ')
DOCUMENTS_URL = env.str('DOCUMENTS_URL')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

ALLOWED_HOSTS = ["*"]

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY', 'b2ejo(#-&pl=98)qtqjmi_is25l80m5(g#t$y@+p#=!fb$2ew6'
)

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'rest_framework',
    'rest_framework_gis',
    'django_filters',
    'django.contrib.gis',
    'support',
    'auth_jwt',
    'authorization',
    'priority_monitoring',
    'funai',
    'monitoring',
    'priority_alerts',
    'catalog',
    'land_use',
    'documental',
    'deter_monitoring',
    'user_profile',
    'corsheaders',
    'scripts',
    'rolepermissions',
    'dashboard',
    'portal.apps.PortalConfig',
    'admin_panel',
]

MIDDLEWARE = [
    'cmr2_api.middleware.DisableJWTOnPublicRoutesMiddleware',
    'cmr2_api.middleware.DisableJWTOnPublicRoutesMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'cmr2_api.middleware.GlobalMiddleware',

]

ROOT_URLCONF = 'cmr2_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'media')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cmr2_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'cmr_funai',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': '192.168.20.135',
        'PORT': '5433',
    },
    'db_for_read': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': DB_NAME_FOR_READ,
        'USER': DB_USER_FOR_READ,
        'PASSWORD': DB_PASSWORD_FOR_READ,
        'HOST': DB_HOST_FOR_READ,
        'PORT': DB_PORT_FOR_READ,
    },
}

DOCUMENTS_URL = os.getenv(
    'DOCUMENTS_URL', 'https://cmr.funai.gov.br/api/media/')

DATABASE_ROUTERS = [
    'cmr2_api.database_routers.CatalogRouters.CatalogRouter',
    'cmr2_api.database_routers.DocumentalRouters.DocumentalRouter',
    'cmr2_api.database_routers.DeterMonitoringRouters.DeterMonitoringRouter',
    'cmr2_api.database_routers.LandUseRouters.LandUseRouter',
    'cmr2_api.database_routers.MonitoringRouters.MonitoringRouter',
    'cmr2_api.database_routers.PriorityAlertsRouters.PriorityAlertsRouter',
    'cmr2_api.database_routers.PriorityMonitoringRouters.\
PriorityMonitoringRouter',
]

# Default auto field
# https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Media files configuration

# Path where media is stored
MEDIA_ROOT = (os.path.join(BASE_DIR, 'media/'))

# Base URL to serve media files
MEDIA_URL = '/media/'

# Django Cors Headers
# https://github.com/adamchainz/django-cors-headers

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# djangorestframework authentication
# https://www.django-rest-framework.org/api-guide/authentication/

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework_csv.renderers.CSVRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework_gis.schema.GeoFeatureAutoSchema',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

}


# djangorestframework-simplejwt token configuration
# https://github.com/jazzband/djangorestframework-simplejwt

SIMPLE_JWT = {
    # 🦆 VOLTAR PARA 15 MINUTOS DEPOIS
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=999999999),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

TEST_RUNNER = 'cmr2_api.test_settings.ManagedModelTestRunner'


################################################################################
####                           LDAP CONFIGURATION                           ####
################################################################################

AUTH_LDAP_SERVER_URI = LDAP_URI

AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "OU=FUNAI,DC=funai,DC=local", ldap.SCOPE_SUBTREE, "(mail=%(user)s)"
)

AUTH_LDAP_START_TLS = False

AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_REFERRALS: 0,
}

# Populate the Django user from the LDAP directory.
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
}

AUTH_LDAP_ALWAYS_UPDATE_USER = True

AUTH_LDAP_FIND_GROUP_PERMS = True
AUTH_LDAP_CACHE_TIMEOUT = 3600

AUTHENTICATION_BACKENDS = (
    'cmr2_api.auth_backends.MyLDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

################################################################################
####                        END LDAP CONFIGURATION                          ####
################################################################################

################################################################################
####                         LOGGING CONFIGURATION                         #####
################################################################################


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'apscheduler': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Configuração para capturar logs de todos os módulos
logging.config.dictConfig(LOGGING)

################################################################################
####                       END LOGGING CONFIGURATION                       #####
################################################################################

# JAZZMIN_UI_TWEAKS = {
#     'navbar_small_text': False,
#     'footer_small_text': False,
#     'body_small_text': False,
#     'brand_small_text': False,
#     'brand_colour': False,
#     'accent': 'accent-info',
#     'navbar': 'navbar-dark',
#     'no_navbar_border': False,
#     'navbar_fixed': True,
#     'layout_boxed': False,
#     'footer_fixed': False,
#     'sidebar_fixed': False,
#     'sidebar': 'sidebar-dark-primary',
#     'sidebar_nav_small_text': True,
#     'sidebar_disable_expand': False,
#     'sidebar_nav_child_indent': False,
#     'sidebar_nav_compact_style': False,
#     'sidebar_nav_legacy_style': False,
#     'sidebar_nav_flat_style': True,
#     'theme': 'solar',
#     'dark_mode_theme': 'darkly',
#     'button_classes': {
#         'primary': 'btn-primary',
#         'secondary': 'btn-secondary',
#         'info': 'btn-info',
#         'warning': 'btn-warning',
#         'danger': 'btn-danger',
#         'success': 'btn-success'
#     },
#     'actions_sticky_top': True
# }

################################################################################
####                           EMAIL CONFIGURATION                          ####
################################################################################

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = '10.0.0.22'
EMAIL_PORT = '25'
EMAIL_SUBJECT_PREFIX = '[CMR] Centro de Monitoramento Remoto'
EMAIL_ADMIN_FEEDBACK = "cmr@funai.gov.br"
DEFAULT_FROM_EMAIL = "cmr@funai.gov.br"

################################################################################
####                           END EMAIL CONFIGURATION                      ####
################################################################################

################################################################################
####                       PERMISSIONS MODULE CONFIGURATION                 ####
################################################################################

ROLEPERMISSIONS_MODULE = 'cmr2_api.roles'

################################################################################
####                    END PERMISSIONS MODULE CONFIGURATION                ####
################################################################################
