"""
Django settings for cmr2_api project.

Generated by 'django-admin startproject' using Django 1.11.29.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

ALLOWED_HOSTS = ["*"]

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY', 'b2ejo(#-&pl=98)qtqjmi_is25l80m5(g#t$y@+p#=!fb$2ew6'
)

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'rest_framework',
    'rest_framework_gis',
    'django_filters',
    'django.contrib.gis',
    'support',
    'auth_jwt',
    'authorization',
    'priority_monitoring',
    'funai',
    'monitoring',
    'priority_alerts',
    'catalog',
    'land_use',
    'documental',
    'deter_monitoring',
    'user_profile',
    'corsheaders',
    'scripts',
    'rolepermissions',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'cmr2_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cmr2_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'cmr_funai',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': '192.168.20.135',
        'PORT': '5433',
        'TEST': {'NAME': 'test_default_db', },
    },
    'db_for_read': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.getenv('DB_NAME_FOR_READ'),
        'USER': os.getenv('DB_USER_FOR_READ'),
        'PASSWORD': os.getenv('DB_PASSWORD_FOR_READ'),
        'HOST': os.getenv('DB_HOST_FOR_READ'),
        'PORT': os.getenv('DB_PORT_FOR_READ', '5432')
    },
}

DOCUMENTS_URL = os.getenv(
    'DOCUMENTS_URL', 'https://cmr.funai.gov.br/api/media/')

DATABASE_ROUTERS = [
    'cmr2_api.database_routers.CatalogRouters.CatalogRouter',
    'cmr2_api.database_routers.DocumentalRouters.DocumentalRouter',
    'cmr2_api.database_routers.DeterMonitoringRouters.DeterMonitoringRouter',
    'cmr2_api.database_routers.LandUseRouters.LandUseRouter',
    'cmr2_api.database_routers.MonitoringRouters.MonitoringRouter',
    'cmr2_api.database_routers.PriorityAlertsRouters.PriorityAlertsRouter',
    'cmr2_api.database_routers.PriorityMonitoringRouters.\
PriorityMonitoringRouter',
]

# Default auto field
# https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Media files configuration

# Path where media is stored
MEDIA_ROOT = (os.path.join(BASE_DIR, 'media/'))

# Base URL to serve media files
MEDIA_URL = '/media/'

# Django Cors Headers
# https://github.com/adamchainz/django-cors-headers

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# djangorestframework authentication
# https://www.django-rest-framework.org/api-guide/authentication/

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework_csv.renderers.CSVRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework_gis.schema.GeoFeatureAutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# djangorestframework-simplejwt token configuration
# https://github.com/jazzband/djangorestframework-simplejwt

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

TEST_RUNNER = 'cmr2_api.test_settings.ManagedModelTestRunner'

# Django Jazzmin settings
# https://django-jazzmin.readthedocs.io/configuration/

JAZZMIN_ADMIN_SITE_TITLE = os.getenv(
    'JAZZMIN_ADMIN_SITE_TITLE', 'CMR ADMIN')
JAZZMIN_ADMIN_SITE_HEADER = os.getenv(
    'JAZZMIN_ADMIN_SITE_HEADER', 'CMR ADMIN')
JAZZMIN_ADMIN_SITE_BRAND = os.getenv('JAZZMIN_ADMIN_SITE_BRAND', 'CMR')
JAZZMIN_ADMIN_SITE_LOGO = os.getenv(
    'JAZZMIN_ADMIN_SITE_LOGO')
JAZZMIN_ADMIN_LOGIN_LOGO = os.getenv(
    'JAZZMIN_ADMIN_LOGIN_LOGO')
JAZZMIN_ADMIN_SITE_FAVICON = os.getenv(
    'JAZZMIN_ADMIN_SITE_FAVICON', '/admin_files/img/funai.svg')


JAZZMIN_SETTINGS = {
    'site_title': JAZZMIN_ADMIN_SITE_TITLE,
    'site_header': JAZZMIN_ADMIN_SITE_HEADER,
    'site_brand': JAZZMIN_ADMIN_SITE_BRAND,
    'site_logo': JAZZMIN_ADMIN_SITE_LOGO,  # Top left admin
    'login_logo': JAZZMIN_ADMIN_LOGIN_LOGO,  # Login site
    'login_logo_dark': JAZZMIN_ADMIN_LOGIN_LOGO,  # Login site
    'site_icon': JAZZMIN_ADMIN_SITE_FAVICON,  # Favicon
    'site_logo_classes': 'img-circle bg-light',

    'welcome_sign': 'Admin control panel',
    'show_sidebar': True,
    'navigation_expanded': False,
    'copyright': 'Hex360 Ltda',
    'topmenu_links': [
        {'name': 'Home',  'url': 'admin:index'},
        {'model': 'auth.User'},
    ],
    'icons': {
        'auth': 'fas fa-users',
        'deter_monitoring': 'fas fa-bookmark',
        'funai': 'fas fa-tree',
        'catalog': 'fas fa-file',
        'land_use': 'fas fa-city',
        'support': 'fas fa-layer-group',
        'documental': 'fas fa-book',
        'monitoring': 'fas fa-satellite',
        'priority_alerts': 'fas fa-exclamation-triangle',
        'priority_monitoring': 'fas fa-map',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas',
    'site_logo_classes': 'img-circle bg-light',

}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': False,
    'accent': 'accent-info',
    'navbar': 'navbar-dark',
    'no_navbar_border': False,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': False,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_small_text': True,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': False,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': True,
    'theme': 'solar',
    'dark_mode_theme': 'darkly',
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success'
    },
    'actions_sticky_top': True
}
################################################################################
####                           LDAP CONFIGURATION                           ####
################################################################################
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType, PosixGroupType

AUTH_LDAP_SERVER_URI = "ldap://10.0.0.1:389"

AUTH_LDAP_BIND_DN = "hex@funai.gov.br"
AUTH_LDAP_BIND_PASSWORD = "Monitoramento.2024"

AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "OU=FUNAI,DC=funai,DC=local", ldap.SCOPE_SUBTREE, "(mail=%(user)s)"
)

AUTH_LDAP_START_TLS = False

AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_REFERRALS: 0,
}

# Populate the Django user from the LDAP directory.
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
}

AUTH_LDAP_ALWAYS_UPDATE_USER = True

AUTH_LDAP_FIND_GROUP_PERMS = True
AUTH_LDAP_CACHE_TIMEOUT = 3600

# Keep ModelBackend around for per-user permissions and maybe a local
# superuser.
AUTHENTICATION_BACKENDS = (
    # 'django_auth_ldap.backend.LDAPBackend',
    'cmr2_api.auth_backends.MyLDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django_auth_ldap': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'auth_backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

################ AD LOCAL DA MÁQUINA 192.168.20.136

# AUTH_LDAP_SERVER_URI = 'ldap://192.168.136.128:389'
# AUTH_LDAP_BIND_DN = 'cn=Administrator,cn=users,dc=demo,dc=lab'
# AUTH_LDAP_BIND_PASSWORD = 'Funai@2024'

# AUTH_LDAP_USER_SEARCH = LDAPSearch(
#     'ou=funai,dc=demo,dc=lab',
#     ldap.SCOPE_SUBTREE,
#     '(mail=%(user)s)'
# )

# AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
#     'dc=demo,dc=lab',
#     ldap.SCOPE_SUBTREE,
#     '(objectClass=top)'
# )

# AUTH_LDAP_GROUP_TYPE = GroupOfNamesType(name_attr="cn")

# AUTH_LDAP_MIRROR_GROUPS = True

# # Populate the Django user from the LDAP directory.
# AUTH_LDAP_ALWAYS_UPDATE_USER = True
# AUTH_LDAP_FIND_GROUP_PERMS = False  # Não configurar permissões por grupo

# AUTH_LDAP_CACHE_TIMEOUT = 3600

################################################################################
####                        END LDAP CONFIGURATION                          ####
################################################################################


################################################################################
####                           EMAIL CONFIGURATION                          ####
################################################################################

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = '10.0.0.22'
EMAIL_PORT = '25'
EMAIL_SUBJECT_PREFIX = '[CMR] Centro de Monitoramento Remoto'
EMAIL_ADMIN_FEEDBACK = "hexgisdev@gmail.com"
DEFAULT_FROM_EMAIL = "hexgisdev@gmail.com"

################################################################################
####                           END EMAIL CONFIGURATION                      ####
################################################################################

################################################################################
####                       PERMISSIONS MODULE CONFIGURATION                 ####
################################################################################

ROLEPERMISSIONS_MODULE = 'cmr2_api.roles'

################################################################################
####                    END PERMISSIONS MODULE CONFIGURATION                ####
################################################################################