# Generated by Django 3.2.3 on 2024-08-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocsAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_action', models.IntegerField(unique=True, verbose_name='Identificador da Ação')),
                ('no_action', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('dt_creation', models.DateTimeField(blank=True, null=True, verbose_name='Data de Registro')),
                ('action_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Ação')),
                ('action_type_group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo com Tipos de Ação')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Descrição da Ação')),
            ],
            options={
                'verbose_name': 'Document Action',
                'verbose_name_plural': 'Documents Actions',
                'ordering': ['action_type'],
            },
        ),
        migrations.CreateModel(
            name='UsersCMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(unique=True, verbose_name='Identificador do Usuário')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome de quem se inscreveu')),
            ],
            options={
                'verbose_name': 'User CMR',
                'verbose_name_plural': 'Users CMR',
            },
        ),
        migrations.CreateModel(
            name='DocsMapoteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.IntegerField(verbose_name='Identificador Chave')),
                ('path_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho do arquivo do documento')),
                ('no_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Documento')),
                ('st_available', models.BooleanField(blank=True, default=False, null=True, verbose_name='Documento disponível')),
                ('st_excluded', models.BooleanField(blank=True, default=False, null=True, verbose_name='Documento excluído')),
                ('dt_registration', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro do documento')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Código Funai – Terras Indígenas')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome das Terras Indígenas')),
                ('co_cr', models.BigIntegerField(blank=True, null=True, verbose_name='Código de Coordenação Regional')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Coordenação Regional')),
                ('no_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do arquivo')),
                ('map_dimension', models.CharField(blank=True, max_length=2, null=True, verbose_name='Dimensão da página do mapa')),
                ('js_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Matriz de Terras Indígenas')),
                ('file', models.FileField(default='Undefined File', upload_to='DocsMapoteca/', verbose_name='Caminho do Aqruivo')),
                ('action_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documental.docsaction')),
                ('usercmr_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documental.userscmr')),
            ],
            options={
                'verbose_name': 'Document Mapoteca',
                'verbose_name_plural': 'Documents Mapoteca',
            },
        ),
        migrations.CreateModel(
            name='DocsLandUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.IntegerField(verbose_name='Identificador Chave')),
                ('path_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho do arquivo do documento')),
                ('no_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Documento')),
                ('st_available', models.BooleanField(blank=True, default=False, null=True, verbose_name='Documento disponível')),
                ('st_excluded', models.BooleanField(blank=True, default=False, null=True, verbose_name='Documento excluído')),
                ('dt_registration', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro do documento')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Código Funai – Terras Indígenas')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome das Terras Indígenas')),
                ('co_cr', models.BigIntegerField(blank=True, null=True, verbose_name='Código de Coordenação Regional')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Coordenação Regional')),
                ('nu_year', models.IntegerField(blank=True, null=True, verbose_name='Ano de referência de entrega')),
                ('nu_year_map', models.IntegerField(blank=True, null=True, verbose_name='Ano do mapa')),
                ('file', models.FileField(default='Undefined File', upload_to='DocsLandUser/', verbose_name='Caminho do arquivo')),
                ('action_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documental.docsaction')),
                ('usercmr_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documental.userscmr')),
            ],
            options={
                'verbose_name': 'Document Land User',
                'verbose_name_plural': 'Documents Land User',
            },
        ),
        migrations.CreateModel(
            name='DocsDocumentTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.IntegerField(verbose_name='Identificador Chave')),
                ('path_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho do arquivo do documento')),
                ('no_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Documento')),
                ('st_available', models.BooleanField(blank=True, default=False, null=True, verbose_name='Documento disponível')),
                ('st_excluded', models.BooleanField(blank=True, default=False, null=True, verbose_name='Documento excluído')),
                ('dt_registration', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro do documento')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='Data da última atualização')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Código Funai – Terras Indígenas')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome das Terras Indígenas')),
                ('co_cr', models.BigIntegerField(blank=True, null=True, verbose_name='Código de Coordenação Regional')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Coordenação Regional')),
                ('dt_document', models.DateField(blank=True, null=True, verbose_name='Data do documento')),
                ('no_extension', models.CharField(blank=True, max_length=255, null=True, verbose_name='Extensão do documento')),
                ('file', models.FileField(default='Undefined File', upload_to='DocumentTI/', verbose_name='Caminho do Arquivo')),
                ('action_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documental.docsaction')),
                ('usercmr_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documental.userscmr')),
            ],
            options={
                'verbose_name': 'Document Indigenous Lands',
                'verbose_name_plural': 'Documents Indigenous Lands',
            },
        ),
    ]
