# Generated by Django 3.2.3 on 2022-06-22 18:34

from django.db import migrations, models
import django.db.models.deletion
import documental.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_acao', models.CharField(max_length=255, unique=True, verbose_name='Action name')),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True, verbose_name='Registration date')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='User id key')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of who registered')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='MapasUsoOcupacaoSolo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Primary key')),
                ('path_documento', models.FileField(max_length=255, upload_to=documental.utils.diretorio_mapas_uso_solo, verbose_name='Document path')),
                ('no_documento', models.CharField(blank=True, max_length=555, null=True, verbose_name='Document name')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Funai code - Indigenou Lands')),
                ('st_disponivel', models.BooleanField(blank=True, default=False, null=True, verbose_name='Document available')),
                ('st_excluido', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted document')),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True, verbose_name='Document registration date')),
                ('dt_atualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Last update date')),
                ('dt_documento', models.DateField(blank=True, null=True, verbose_name='Date of document')),
                ('nu_ano', models.IntegerField(blank=True, null=True, verbose_name='Delivery reference year')),
                ('nu_ano_mapa', models.IntegerField(blank=True, null=True, verbose_name='Year of the map')),
                ('tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Maps_type', to='documental.action')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Maps_usuario_id', to='documental.usuario')),
            ],
            options={
                'verbose_name': 'Use Land Occupancy Map',
                'verbose_name_plural': 'Use Land Occupancy Maps',
            },
        ),
        migrations.CreateModel(
            name='DocumentosTI',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Primary key')),
                ('path_documento', models.FileField(max_length=255, upload_to=documental.utils.diretorio_ti, verbose_name='Document path')),
                ('no_documento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document name')),
                ('no_extensao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document extension')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Funai code - Indigenou Lands')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indigenou Lands name')),
                ('st_disponivel', models.BooleanField(blank=True, default=False, null=True, verbose_name='Document available')),
                ('st_excluido', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted document')),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True, verbose_name='Document registration date')),
                ('dt_atualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Last update date')),
                ('dt_documento', models.DateField(blank=True, null=True, verbose_name='Date of document')),
                ('acao_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentosti_type', to='documental.action')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentosti_usuario_id', to='documental.usuario')),
            ],
            options={
                'verbose_name': 'DocumentTI',
                'verbose_name_plural': 'DocumentsTI',
            },
        ),
        migrations.CreateModel(
            name='DocumentalDocs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Primary key')),
                ('path_documento', models.FileField(max_length=255, upload_to=documental.utils.diretorio_ti, verbose_name='Document path')),
                ('no_documento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document name')),
                ('st_disponivel', models.BooleanField(blank=True, default=False, null=True, verbose_name='Document available')),
                ('st_excluido', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted document')),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True, verbose_name='Document registration date')),
                ('dt_atualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Last update date')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Funai code - Indigenou Lands')),
                ('no_extensao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document extension')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indigenou Lands name')),
                ('dt_documento', models.DateField(blank=True, null=True, verbose_name='Date of document')),
                ('nu_ano', models.IntegerField(blank=True, null=True, verbose_name='Delivery reference year')),
                ('nu_ano_mapa', models.IntegerField(blank=True, null=True, verbose_name='Year of the map')),
                ('acao_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentosdocs_type', to='documental.action')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentosdocs_usuario_id', to='documental.usuario')),
            ],
            options={
                'verbose_name': 'Documental Doc',
                'verbose_name_plural': 'Documental Docs',
            },
        ),
    ]
