# Generated by Django 3.2.3 on 2022-06-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapasusoocupacaosolo',
            name='tipo_id',
        ),
        migrations.RemoveField(
            model_name='mapasusoocupacaosolo',
            name='usuario_id',
        ),
        migrations.DeleteModel(
            name='DocumentosTI',
        ),
        migrations.DeleteModel(
            name='MapasUsoOcupacaoSolo',
        ),
    ]
