# Generated by Django 3.2.3 on 2022-06-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaldocs',
            name='co_cr',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Regional Coordenation code'),
        ),
        migrations.AddField(
            model_name='documentaldocs',
            name='ds_cr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordenation name'),
        ),
        migrations.AlterField(
            model_name='documentaldocs',
            name='path_documento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document path'),
        ),
        migrations.AlterField(
            model_name='documentosti',
            name='path_documento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document path'),
        ),
        migrations.AlterField(
            model_name='mapasusoocupacaosolo',
            name='path_documento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document path'),
        ),
    ]
