# Generated by Django 3.2.3 on 2022-07-06 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0002_auto_20220624_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_acao', models.CharField(max_length=255, unique=True, verbose_name='Action name')),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True, verbose_name='Registration date')),
                ('descricao', models.CharField(blank=True, max_length=512, null=True, verbose_name='Description of documental type')),
            ],
            options={
                'verbose_name': 'Document Action',
                'verbose_name_plural': 'Documents Actions',
            },
        ),
        migrations.RemoveField(
            model_name='documentaldocs',
            name='acao_id',
        ),
        migrations.RemoveField(
            model_name='documentaldocs',
            name='no_cr',
        ),
        migrations.AddField(
            model_name='documentaldocs',
            name='ds_cr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordenation name'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.AddField(
            model_name='documentaldocs',
            name='id_acao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentosdocs_action', to='documental.docsaction'),
        ),
    ]
