# Generated by Django 3.2.3 on 2022-07-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0003_auto_20220706_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docsaction',
            name='dt_cadastro',
        ),
        migrations.AddField(
            model_name='docsaction',
            name='dt_criacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='docsaction',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Action id key'),
        ),
        migrations.AlterField(
            model_name='documentaldocs',
            name='usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentosdocs_usuario_id', to='documental.usuario'),
        ),
    ]
