# Generated by Django 3.2.3 on 2022-08-31 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0004_auto_20220718_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(unique=True, verbose_name='Identifier User')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of who registered')),
            ],
            options={
                'verbose_name': 'User CMR',
                'verbose_name_plural': 'Users CMR',
            },
        ),
        migrations.RenameField(
            model_name='docsaction',
            old_name='dt_criacao',
            new_name='dt_creation',
        ),
        migrations.RenameField(
            model_name='docsaction',
            old_name='no_acao',
            new_name='no_action',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='id_acao',
            new_name='action_id',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='dt_documento',
            new_name='dt_document',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='dt_cadastro',
            new_name='dt_registration',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='dt_atualizacao',
            new_name='dt_update',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='no_documento',
            new_name='no_document',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='no_extensao',
            new_name='no_extension',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='nu_ano',
            new_name='nu_year',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='nu_ano_mapa',
            new_name='nu_year_map',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='st_disponivel',
            new_name='st_available',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='st_excluido',
            new_name='st_excluded',
        ),
        migrations.RemoveField(
            model_name='docsaction',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='documentaldocs',
            name='path_documento',
        ),
        migrations.RemoveField(
            model_name='documentaldocs',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='docsaction',
            name='action_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of action'),
        ),
        migrations.AddField(
            model_name='docsaction',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Description of action'),
        ),
        migrations.AddField(
            model_name='docsaction',
            name='id_action',
            field=models.IntegerField(default=1, unique=True, verbose_name='Identifier Action'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentaldocs',
            name='id_document',
            field=models.IntegerField(default=2, verbose_name='Identifier key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentaldocs',
            name='path_document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document file path'),
        ),
        migrations.AlterField(
            model_name='docsaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentaldocs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='documentaldocs',
            name='usercmr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentosdocs_usercmr', to='documental.userscmr'),
        ),
    ]
