# Generated by Django 3.2.3 on 2022-08-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0004_auto_20220718_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsaction',
            name='id_action',
            field=models.IntegerField(default=9999, unique=True, verbose_name='Action id key'),
        ),
        migrations.AddField(
            model_name='documentaldocs',
            name='id_document',
            field=models.IntegerField(default=4572, unique=True, verbose_name='Primary key'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_user',
            field=models.IntegerField(default=494, unique=True, verbose_name='User id key'),
        ),
        migrations.AlterField(
            model_name='docsaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentaldocs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
