# Generated by Django 3.2.3 on 2022-09-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0005_auto_20220831_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsDocumentTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.IntegerField(verbose_name='Key Identifier')),
                ('path_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document file path')),
                ('no_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document name')),
                ('st_available', models.BooleanField(blank=True, default=False, null=True, verbose_name='Document available')),
                ('st_excluded', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted document')),
                ('dt_registration', models.DateTimeField(blank=True, null=True, verbose_name='Document registration date')),
                ('dt_update', models.DateTimeField(blank=True, null=True, verbose_name='Last update date')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Funai code - Indigenous Lands')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indigenous Lands name')),
                ('co_cr', models.BigIntegerField(blank=True, null=True, verbose_name='Regional Coordenation code')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordenation name')),
                ('dt_document', models.DateField(blank=True, null=True, verbose_name='Date of document')),
                ('no_extension', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document extension')),
            ],
            options={
                'verbose_name': 'Document Indigenous Lands',
                'verbose_name_plural': 'Documents Indigenous Lands',
            },
        ),
        migrations.CreateModel(
            name='DocsLandUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.IntegerField(verbose_name='Key Identifier')),
                ('path_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document file path')),
                ('no_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document name')),
                ('st_available', models.BooleanField(blank=True, default=False, null=True, verbose_name='Document available')),
                ('st_excluded', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted document')),
                ('dt_registration', models.DateTimeField(blank=True, null=True, verbose_name='Document registration date')),
                ('dt_update', models.DateTimeField(blank=True, null=True, verbose_name='Last update date')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Funai code - Indigenous Lands')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indigenous Lands name')),
                ('co_cr', models.BigIntegerField(blank=True, null=True, verbose_name='Regional Coordenation code')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordenation name')),
                ('nu_year', models.IntegerField(blank=True, null=True, verbose_name='Delivery reference year')),
                ('nu_year_map', models.IntegerField(blank=True, null=True, verbose_name='Year of the map')),
            ],
            options={
                'verbose_name': 'Document Land User',
                'verbose_name_plural': 'Documents Land User',
            },
        ),
        migrations.CreateModel(
            name='DocsMapoteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.IntegerField(verbose_name='Key Identifier')),
                ('path_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document file path')),
                ('no_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document name')),
                ('st_available', models.BooleanField(blank=True, default=False, null=True, verbose_name='Document available')),
                ('st_excluded', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted document')),
                ('dt_registration', models.DateTimeField(blank=True, null=True, verbose_name='Document registration date')),
                ('dt_update', models.DateTimeField(blank=True, null=True, verbose_name='Last update date')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Funai code - Indigenous Lands')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indigenous Lands name')),
                ('co_cr', models.BigIntegerField(blank=True, null=True, verbose_name='Regional Coordenation code')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordenation name')),
                ('no_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Description')),
                ('map_dimension', models.CharField(blank=True, max_length=2, null=True, verbose_name='Map page dimension')),
                ('js_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Array de Terras Indígenas')),
            ],
            options={
                'verbose_name': 'Document Mapoteca',
                'verbose_name_plural': 'Documents Mapoteca',
            },
        ),
        migrations.AlterModelOptions(
            name='docsaction',
            options={'ordering': ['action_type'], 'verbose_name': 'Document Action', 'verbose_name_plural': 'Documents Actions'},
        ),
        migrations.AddField(
            model_name='docsaction',
            name='action_type_group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Group within action types'),
        ),
        migrations.AlterField(
            model_name='docsaction',
            name='id_action',
            field=models.IntegerField(unique=True, verbose_name='Action Identifier'),
        ),
        migrations.AlterField(
            model_name='userscmr',
            name='id_user',
            field=models.IntegerField(unique=True, verbose_name='User Identifier'),
        ),
        migrations.DeleteModel(
            name='DocumentalDocs',
        ),
        migrations.AddField(
            model_name='docsmapoteca',
            name='action_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documental.docsaction'),
        ),
        migrations.AddField(
            model_name='docsmapoteca',
            name='usercmr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documental.userscmr'),
        ),
        migrations.AddField(
            model_name='docslanduser',
            name='action_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documental.docsaction'),
        ),
        migrations.AddField(
            model_name='docslanduser',
            name='usercmr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documental.userscmr'),
        ),
        migrations.AddField(
            model_name='docsdocumentti',
            name='action_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documental.docsaction'),
        ),
        migrations.AddField(
            model_name='docsdocumentti',
            name='usercmr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documental.userscmr'),
        ),
    ]
