# Generated by Django 3.2.3 on 2022-08-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0005_auto_20220829_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(default=494, unique=True, verbose_name='Identifier User')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of who registered')),
            ],
            options={
                'verbose_name': 'User CMR',
                'verbose_name_plural': 'Users CMR',
            },
        ),
        migrations.AlterField(
            model_name='documentaldocs',
            name='id_acao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temp'),
        ),
        migrations.AlterField(
            model_name='documentaldocs',
            name='usuario_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temp'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
