# Generated by Django 3.2.3 on 2022-11-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0006_auto_20220922_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsdocumentti',
            name='file',
            field=models.FileField(default='Undefined File', upload_to='DocumentTI/', verbose_name='Docs DocumentTI file path'),
        ),
        migrations.AddField(
            model_name='docslanduser',
            name='file',
            field=models.FileField(default='Undefined File', upload_to='DocsLandUser/', verbose_name='Docs DocumentTI file path'),
        ),
        migrations.AddField(
            model_name='docsmapoteca',
            name='file',
            field=models.FileField(default='Undefined File', upload_to='DocsMapoteca/', verbose_name='Docs DocsMapoteca file path'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='dt_registration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Document registration date'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='dt_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update date'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='dt_registration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Document registration date'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='dt_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update date'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='dt_registration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Document registration date'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='dt_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update date'),
        ),
    ]
