# Generated by Django 3.2.3 on 2022-08-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0006_auto_20220829_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentaldocs',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='documentaldocs',
            name='action_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentosdocs_action', to='documental.docsaction'),
        ),
        migrations.AddField(
            model_name='documentaldocs',
            name='usercmr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentosdocs_usercmr', to='documental.userscmr'),
        ),
        migrations.AlterField(
            model_name='docsaction',
            name='id_action',
            field=models.IntegerField(unique=True, verbose_name='Action id key'),
        ),
        migrations.AlterField(
            model_name='documentaldocs',
            name='id_document',
            field=models.IntegerField(unique=True, verbose_name='Primary key'),
        ),
        migrations.AlterField(
            model_name='userscmr',
            name='id_user',
            field=models.IntegerField(unique=True, verbose_name='Identifier User'),
        ),
    ]
