# Generated by Django 3.2.3 on 2022-08-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0007_auto_20220829_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docsaction',
            old_name='dt_criacao',
            new_name='dt_creation',
        ),
        migrations.RenameField(
            model_name='docsaction',
            old_name='no_acao',
            new_name='no_action',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='dt_documento',
            new_name='dt_document',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='dt_cadastro',
            new_name='dt_registration',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='dt_atualizacao',
            new_name='dt_update',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='no_documento',
            new_name='no_document',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='no_extensao',
            new_name='no_extension',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='nu_ano',
            new_name='nu_year',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='nu_ano_mapa',
            new_name='nu_year_map',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='st_disponivel',
            new_name='st_available',
        ),
        migrations.RenameField(
            model_name='documentaldocs',
            old_name='st_excluido',
            new_name='st_excluded',
        ),
        migrations.RemoveField(
            model_name='docsaction',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='documentaldocs',
            name='id_acao',
        ),
        migrations.RemoveField(
            model_name='documentaldocs',
            name='path_documento',
        ),
        migrations.AddField(
            model_name='docsaction',
            name='action_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of action'),
        ),
        migrations.AddField(
            model_name='docsaction',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Description of action'),
        ),
        migrations.AddField(
            model_name='documentaldocs',
            name='path_document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document file path'),
        ),
        migrations.AlterField(
            model_name='docsaction',
            name='id_action',
            field=models.IntegerField(unique=True, verbose_name='Identifier Action'),
        ),
        migrations.AlterField(
            model_name='documentaldocs',
            name='id_document',
            field=models.IntegerField(verbose_name='Identifier key'),
        ),
    ]
