# Generated by Django 3.2.3 on 2024-07-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0007_auto_20221129_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsaction',
            name='action_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Ação'),
        ),
        migrations.AlterField(
            model_name='docsaction',
            name='action_type_group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo com Tipos de Ação'),
        ),
        migrations.AlterField(
            model_name='docsaction',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Descrição da Ação'),
        ),
        migrations.AlterField(
            model_name='docsaction',
            name='dt_creation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='docsaction',
            name='id_action',
            field=models.IntegerField(unique=True, verbose_name='Identificador da Ação'),
        ),
        migrations.AlterField(
            model_name='docsaction',
            name='no_action',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='co_cr',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Código de Coordenação Regional'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='co_funai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Funai – Terras Indígenas'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='ds_cr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Coordenação Regional'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='dt_document',
            field=models.DateField(blank=True, null=True, verbose_name='Data do documento'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='dt_registration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de registro do documento'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='dt_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='file',
            field=models.FileField(default='Undefined File', upload_to='DocumentTI/', verbose_name='Caminho do Arquivo'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='id_document',
            field=models.IntegerField(verbose_name='Identificador Chave'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='no_document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Documento'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='no_extension',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extensão do documento'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='no_ti',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome das Terras Indígenas'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='path_document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho do arquivo do documento'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='st_available',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Documento disponível'),
        ),
        migrations.AlterField(
            model_name='docsdocumentti',
            name='st_excluded',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Documento excluído'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='co_cr',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Código de Coordenação Regional'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='co_funai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Funai – Terras Indígenas'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='ds_cr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Coordenação Regional'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='dt_registration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de registro do documento'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='dt_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='file',
            field=models.FileField(default='Undefined File', upload_to='DocsLandUser/', verbose_name='Caminho do arquivo'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='id_document',
            field=models.IntegerField(verbose_name='Identificador Chave'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='no_document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Documento'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='no_ti',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome das Terras Indígenas'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='nu_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de referência de entrega'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='nu_year_map',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano do mapa'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='path_document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho do arquivo do documento'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='st_available',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Documento disponível'),
        ),
        migrations.AlterField(
            model_name='docslanduser',
            name='st_excluded',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Documento excluído'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='co_cr',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Código de Coordenação Regional'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='co_funai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Funai – Terras Indígenas'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='ds_cr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Coordenação Regional'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='dt_registration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de registro do documento'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='dt_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='file',
            field=models.FileField(default='Undefined File', upload_to='DocsMapoteca/', verbose_name='Caminho do Aqruivo'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='id_document',
            field=models.IntegerField(verbose_name='Identificador Chave'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='js_ti',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Matriz de Terras Indígenas'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='map_dimension',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Dimensão da página do mapa'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='no_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do arquivo'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='no_document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Documento'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='no_ti',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome das Terras Indígenas'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='path_document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho do arquivo do documento'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='st_available',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Documento disponível'),
        ),
        migrations.AlterField(
            model_name='docsmapoteca',
            name='st_excluded',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Documento excluído'),
        ),
        migrations.AlterField(
            model_name='userscmr',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome de quem se inscreveu'),
        ),
        migrations.AlterField(
            model_name='userscmr',
            name='id_user',
            field=models.IntegerField(unique=True, verbose_name='Identificador do Usuário'),
        ),
    ]
