# Generated by Django 3.2.3 on 2025-05-29 15:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenacaoRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_cr', models.BigIntegerField(blank=True, default=1, null=True, unique=True, verbose_name='COD Coordenção Regional')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Coordenação Regional')),
                ('no_abreviado', models.CharField(blank=True, max_length=255, null=True, verbose_name='UF Coordenação Regional')),
                ('sg_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sigla Coordenação Regional')),
                ('st_situacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Situação')),
                ('ds_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('no_regiao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Região')),
                ('no_municipio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('no_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado')),
                ('sg_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='UF')),
                ('ds_telefone', models.CharField(blank=True, max_length=512, null=True, verbose_name='TEL de Contato')),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True, verbose_name='Data Registro')),
            ],
            options={
                'verbose_name': 'Coordenacao Regional',
                'verbose_name_plural': 'Coordenacoes Regionais',
                'db_table': 'funai_coordenacao_regional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LimiteTerraIndigena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4674)),
                ('no_ti', models.CharField(max_length=255, verbose_name='Terra Indígema')),
                ('co_funai', models.IntegerField(unique=True, verbose_name='COD Funai')),
                ('no_grupo_etnico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo Étnico')),
                ('ds_fase_ti', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fase TI')),
                ('ds_modalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidade TI')),
                ('ds_reestudo_ti', models.CharField(blank=True, max_length=80, null=True, verbose_name='Reestudo TI')),
                ('ds_cr', models.CharField(blank=True, max_length=100, null=True)),
                ('no_municipio', models.TextField(blank=True, null=True)),
                ('sg_uf', models.CharField(blank=True, max_length=20, null=True)),
                ('st_faixa_fronteira', models.CharField(blank=True, max_length=3, null=True)),
                ('dt_em_estudo', models.DateField(blank=True, null=True)),
                ('ds_portaria_em_estudo', models.TextField(blank=True, null=True)),
                ('dt_delimitada', models.DateField(blank=True, null=True)),
                ('ds_despacho_delimitada', models.TextField(blank=True, null=True)),
                ('dt_declarada', models.DateField(blank=True, null=True)),
                ('ds_portaria_declarada', models.TextField(blank=True, null=True)),
                ('dt_homologada', models.DateField(blank=True, null=True)),
                ('ds_decreto_homologada', models.TextField(blank=True, null=True)),
                ('dt_regularizada', models.DateField(blank=True, null=True)),
                ('ds_matricula_regularizada', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_em_estudo', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_delimitada', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_declarada', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_homologada', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_regularizada', models.TextField(blank=True, null=True)),
                ('nu_area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True)),
                ('possui_ig', models.BooleanField(default=False)),
                ('co_cr', models.ForeignKey(db_column='co_cr', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='terras_indigenas', to='funai.coordenacaoregional', to_field='co_cr')),
            ],
            options={
                'verbose_name': 'Terra Indigena',
                'verbose_name_plural': 'Terras Indigenas',
                'db_table': 'funai_terra_indigena',
                'ordering': ('no_ti',),
                'managed': True,
            },
        ),
    ]
