# Generated by Django 3.2.3 on 2025-01-09 11:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenacaoRegional',
            fields=[
                ('co_cr', models.BigIntegerField(default=1, primary_key=True, serialize=False, unique=True, verbose_name='COD Coordenção Regional')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Coordenação Regional')),
                ('no_abreviado', models.CharField(blank=True, max_length=255, null=True, verbose_name='UF Coordenação Regional')),
                ('sg_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sigla Coordenação Regional')),
                ('st_situacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Situação')),
                ('ds_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('no_regiao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Região')),
                ('no_municipio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('no_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado')),
                ('sg_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='UF')),
                ('ds_telefone', models.CharField(blank=True, max_length=512, null=True, verbose_name='TEL de Contato')),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True, verbose_name='Data Registro')),
            ],
            options={
                'verbose_name': 'Coordenacao Regional',
                'verbose_name_plural': 'Coordenacoes Regionais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LimiteTerraIndigena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4674)),
                ('no_ti', models.CharField(max_length=255, verbose_name='Terra Indígema')),
                ('co_funai', models.IntegerField(unique=True, verbose_name='COD Funai')),
                ('no_grupo_etnico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo Étnico')),
                ('ds_fase_ti', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fase TI')),
                ('ds_modalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidade TI')),
                ('ds_reestudo_ti', models.CharField(blank=True, max_length=80, null=True, verbose_name='Reestudo TI')),
                ('ds_cr', models.CharField(blank=True, max_length=100, null=True)),
                ('no_municipio', models.TextField(blank=True, null=True)),
                ('sg_uf', models.CharField(blank=True, max_length=20, null=True)),
                ('st_faixa_fronteira', models.CharField(blank=True, max_length=3, null=True)),
                ('dt_em_estudo', models.DateField(blank=True, null=True)),
                ('ds_portaria_em_estudo', models.TextField(blank=True, null=True)),
                ('dt_delimitada', models.DateField(blank=True, null=True)),
                ('ds_despacho_delimitada', models.TextField(blank=True, null=True)),
                ('dt_declarada', models.DateField(blank=True, null=True)),
                ('ds_portaria_declarada', models.TextField(blank=True, null=True)),
                ('dt_homologada', models.DateField(blank=True, null=True)),
                ('ds_decreto_homologada', models.TextField(blank=True, null=True)),
                ('dt_regularizada', models.DateField(blank=True, null=True)),
                ('ds_matricula_regularizada', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_em_estudo', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_delimitada', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_declarada', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_homologada', models.TextField(blank=True, null=True)),
                ('ds_doc_resumo_regularizada', models.TextField(blank=True, null=True)),
                ('nu_area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True)),
                ('possui_ig', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Terra Indigena',
                'verbose_name_plural': 'Terras Indigenas',
                'db_table': 'funai"."lim_terra_indigena_a',
                'ordering': ('no_ti',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentoGestaoFunai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_funai', models.IntegerField(verbose_name='Cod Funai')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Terras Indígena')),
                ('no_regiao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Região')),
                ('sg_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='UF')),
                ('no_povo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Povos')),
                ('no_bioma', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bioma')),
                ('ds_parceiros', models.CharField(blank=True, max_length=255, null=True, verbose_name='Parceiros')),
                ('cr_funai', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Funai')),
                ('no_ig', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instrumento')),
                ('ds_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status')),
                ('nu_ano_elaboracao', models.IntegerField(blank=True, null=True, verbose_name='Elaborado em')),
                ('ds_disp_meio_local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Disponível em')),
                ('ds_tll_publi', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('ds_obs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('dt_cadastro', models.DateField(blank=True, null=True, verbose_name='Data Registro')),
            ],
            options={
                'verbose_name': 'Instrumento de Gestao Funai',
                'verbose_name_plural': 'Instrumentos de Gestao Funai',
            },
        ),
    ]
