# Generated by Django 3.2.3 on 2024-12-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='st_amazonia_legal',
        ),
    ]
