# Generated by Django 3.2.3 on 2021-12-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limiteterraindigena',
            name='co_cr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='co_funai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_cr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_decreto_homologada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_despacho_delimitada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_declarada',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_delimitada',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_em_estudo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_homologada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_regularizada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_fase_ti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_matricula_regularizada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_modalidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_portaria_declarada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_portaria_em_estudo',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_reestudo_ti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='dt_cadastro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='dt_declarada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='dt_delimitada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='dt_em_estudo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='dt_homologada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='dt_regularizada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='id_cont',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='no_grupo_etnico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='no_municipio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='nu_area_ha',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='sg_uf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='st_faixa_fronteira',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
