# Generated by Django 3.2.3 on 2025-05-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenacaoregional',
            options={'managed': True, 'verbose_name': 'Coordenacao Regional', 'verbose_name_plural': 'Coordenacoes Regionais'},
        ),
        migrations.AlterModelOptions(
            name='limiteterraindigena',
            options={'managed': True, 'ordering': ('no_ti',), 'verbose_name': 'Terra Indigena', 'verbose_name_plural': 'Terras Indigenas'},
        ),
    ]
