# Generated by Django 3.2.3 on 2021-12-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0002_auto_20211230_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='co_cr',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
