# Generated by Django 3.2.3 on 2021-12-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0003_alter_limiteterraindigena_co_cr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='id_cont',
        ),
    ]
