# Generated by Django 3.2.3 on 2022-01-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0004_remove_limiteterraindigena_id_cont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='co_cr',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_cr',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_decreto_homologada',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_despacho_delimitada',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_declarada',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_delimitada',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_em_estudo',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_homologada',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_regularizada',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_fase_ti',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_matricula_regularizada',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_modalidade',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_portaria_declarada',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_portaria_em_estudo',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='ds_reestudo_ti',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='dt_cadastro',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='dt_declarada',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='dt_delimitada',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='dt_em_estudo',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='dt_homologada',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='dt_regularizada',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='no_grupo_etnico',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='no_municipio',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='nu_area_ha',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='sg_uf',
        ),
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='st_faixa_fronteira',
        ),
        migrations.AddField(
            model_name='coordenacaoregional',
            name='co_cr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
