# Generated by Django 3.2.3 on 2022-01-03 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0005_auto_20220103_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenacaoregional',
            options={'ordering': ['no_cr'], 'verbose_name': 'CoordenacaoRegional', 'verbose_name_plural': 'CoordenacoesRegionais'},
        ),
        migrations.AlterModelOptions(
            name='limiteterraindigena',
            options={'ordering': ['no_ti'], 'verbose_name': 'LimiteTerraIndigena', 'verbose_name_plural': 'LimitesTerrasIndigenas'},
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='co_cr_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CO_CR_with_CO_TI', to='funai.coordenacaoregional'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='co_cr',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='co_funai',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
