# Generated by Django 3.2.3 on 2022-01-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0006_auto_20220103_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenacaoregional',
            name='ds_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordenacaoregional',
            name='ds_telefone',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='coordenacaoregional',
            name='dt_cadastro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coordenacaoregional',
            name='no_abreviado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordenacaoregional',
            name='no_municipio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordenacaoregional',
            name='no_regiao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordenacaoregional',
            name='no_uf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordenacaoregional',
            name='sg_cr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordenacaoregional',
            name='sg_uf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordenacaoregional',
            name='st_situacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
