# Generated by Django 3.2.3 on 2022-01-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0007_auto_20220103_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='co_cr',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
