# Generated by Django 3.2.3 on 2022-01-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0008_alter_coordenacaoregional_co_cr'),
    ]

    operations = [
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_cr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_fase_ti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_modalidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='nu_area_ha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='sg_uf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='st_faixa_fronteira',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='co_funai',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
