# Generated by Django 3.2.3 on 2022-01-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0011_auto_20220104_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='co_cr',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
