# Generated by Django 3.2.3 on 2022-03-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0013_auto_20220111_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenacaoregional',
            options={'ordering': ('ds_cr',), 'verbose_name': 'CoordenacaoRegional', 'verbose_name_plural': 'CoordenacoesRegionais'},
        ),
        migrations.RemoveField(
            model_name='coordenacaoregional',
            name='no_cr',
        ),
        migrations.AddField(
            model_name='coordenacaoregional',
            name='ds_cr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordenation name'),
        ),
    ]
