# Generated by Django 3.2.3 on 2022-06-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0014_auto_20220307_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='id',
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='co_funai',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True, verbose_name='Funai code'),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='nu_area_ha',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area ha'),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='nu_area_km',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Area km'),
        ),
    ]
