# Generated by Django 3.2.3 on 2024-04-22 18:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0016_auto_20231024_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='limiteterraindigena',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4674),
        ),
    ]
