# Generated by Django 3.2.3 on 2024-06-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0017_limiteterraindigena_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentoGestaoFunai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_funai', models.IntegerField()),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Indigenous Lands')),
                ('no_regiao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Region Name')),
                ('sg_uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='State aconymn')),
                ('no_povo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hamlet Names')),
                ('no_bioma', models.CharField(blank=True, max_length=255, null=True, verbose_name='Biom Name')),
                ('ds_parceiros', models.CharField(blank=True, max_length=255, null=True, verbose_name='Partners')),
                ('cr_funai', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name Funai')),
                ('no_ig', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instrumental Name')),
                ('ds_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='status')),
                ('nu_ano_elaboracao', models.IntegerField(blank=True, null=True, verbose_name='Elaborated in')),
                ('ds_disp_meio_local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Privided by')),
                ('ds_tll_publi', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('ds_obs', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('dt_cadastro', models.DateField(blank=True, null=True, verbose_name='Register Date')),
            ],
        ),
    ]
