# Generated by Django 3.2.3 on 2024-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0018_instrumentogestaofunai'),
    ]

    operations = [
        migrations.AddField(
            model_name='limiteterraindigena',
            name='possui_ig',
            field=models.BooleanField(default=False),
        ),
    ]
