# Generated by Django 3.2.3 on 2024-06-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0019_limiteterraindigena_possui_ig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentogestaofunai',
            name='no_ti',
        ),
        migrations.RemoveField(
            model_name='instrumentogestaofunai',
            name='sg_uf',
        ),
    ]
