# Generated by Django 3.2.3 on 2024-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0020_auto_20240604_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentogestaofunai',
            name='no_ti',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Indigenous Lands'),
        ),
        migrations.AddField(
            model_name='instrumentogestaofunai',
            name='sg_uf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State aconymn'),
        ),
    ]
