# Generated by Django 3.2.3 on 2024-06-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0021_auto_20240604_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limiteterraindigena',
            name='nu_area_km',
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_decreto_homologada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_despacho_delimitada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_declarada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_delimitada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_em_estudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_homologada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_doc_resumo_regularizada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_matricula_regularizada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_portaria_declarada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_portaria_em_estudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='ds_reestudo_ti',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Reestudo TI'),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='dt_cadastro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='dt_declarada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='dt_delimitada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='dt_em_estudo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='dt_homologada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='dt_regularizada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='no_grupo_etnico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo Étnico'),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='no_municipio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limiteterraindigena',
            name='st_amazonia_legal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='co_cr',
            field=models.ForeignKey(db_column='co_cr', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='terras_indigenas', to='funai.coordenacaoregional'),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='co_funai',
            field=models.IntegerField(unique=True, verbose_name='Funai code'),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='ds_cr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='ds_fase_ti',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fase TI'),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='ds_modalidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidade TI'),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='no_ti',
            field=models.CharField(max_length=255, verbose_name='Name of Indigenous Lands'),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='nu_area_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='sg_uf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='st_faixa_fronteira',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
