# Generated by Django 3.2.3 on 2024-07-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0022_auto_20240624_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentogestaofunai',
            options={'verbose_name': 'Management Instrument', 'verbose_name_plural': 'Management Instruments'},
        ),
        migrations.AlterModelTable(
            name='instrumentogestaofunai',
            table='tb_instrumento_gestao_funai',
        ),
    ]
