# Generated by Django 3.2.3 on 2024-06-04 18:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0022_auto_20240604_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4674),
        ),
    ]
