# Generated by Django 3.2.3 on 2024-07-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0023_auto_20240716_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentogestaofunai',
            options={'managed': False, 'verbose_name': 'Management Instrument', 'verbose_name_plural': 'Management Instruments'},
        ),
    ]
