# Generated by Django 3.2.3 on 2024-06-06 19:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0023_alter_limiteterraindigena_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4674, verbose_name='Geometry Field'),
        ),
    ]
