# Generated by Django 3.2.3 on 2024-07-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0024_alter_instrumentogestaofunai_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instrumentogestaofunai',
            table='funai"."tb_instrumento_gestao_funai',
        ),
    ]
