# Generated by Django 3.2.3 on 2024-07-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0025_alter_instrumentogestaofunai_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instrumentogestaofunai',
            table='tb_instrumento_gestao_funai',
        ),
    ]
