# Generated by Django 3.2.3 on 2024-07-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0025_alter_limiteterraindigena_geom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenacaoregional',
            options={'verbose_name': 'Coordenacao Regional', 'verbose_name_plural': 'Coordenacoes Regionais'},
        ),
        migrations.AlterModelOptions(
            name='instrumentogestaofunai',
            options={'verbose_name': 'Instrumento Gestao Funai', 'verbose_name_plural': 'Instrumentos Gestao Funai'},
        ),
        migrations.AlterModelOptions(
            name='limiteterraindigena',
            options={'ordering': ('no_ti',), 'verbose_name': 'Terra Indigena', 'verbose_name_plural': 'Terras Indigenas'},
        ),
    ]
