# Generated by Django 3.2.3 on 2024-07-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0026_alter_instrumentogestaofunai_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentogestaofunai',
            options={'verbose_name': 'Management Instrument', 'verbose_name_plural': 'Management Instruments'},
        ),
    ]
