# Generated by Django 3.2.3 on 2024-07-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funai', '0026_auto_20240709_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentogestaofunai',
            options={'verbose_name': 'Instrumento de Gestao Funai', 'verbose_name_plural': 'Instrumentos de Gestao Funai'},
        ),
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='co_cr',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False, unique=True, verbose_name='COD Coordenção Regional'),
        ),
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='ds_cr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Coordenação Regional'),
        ),
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='ds_telefone',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='TEL de Contato'),
        ),
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='dt_cadastro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Registro'),
        ),
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='no_abreviado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UF Coordenação Regional'),
        ),
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='no_municipio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='no_regiao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='no_uf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='sg_cr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sigla Coordenação Regional'),
        ),
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='sg_uf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='coordenacaoregional',
            name='st_situacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='co_funai',
            field=models.IntegerField(verbose_name='Cod Funai'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='cr_funai',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Funai'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='ds_disp_meio_local',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Disponível em'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='ds_obs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='ds_parceiros',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Parceiros'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='ds_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='dt_cadastro',
            field=models.DateField(blank=True, null=True, verbose_name='Data Registro'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='no_bioma',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bioma'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='no_ig',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instrumento'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='no_povo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Povos'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='no_regiao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='no_ti',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Terras Indígena'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='nu_ano_elaboracao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Elaborado em'),
        ),
        migrations.AlterField(
            model_name='instrumentogestaofunai',
            name='sg_uf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='co_funai',
            field=models.IntegerField(unique=True, verbose_name='COD Funai'),
        ),
        migrations.AlterField(
            model_name='limiteterraindigena',
            name='no_ti',
            field=models.CharField(max_length=255, verbose_name='Terra Indígema'),
        ),
    ]
