# Generated by Django 3.2.3 on 2024-08-01 13:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeterTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Classification classes')),
                ('quadrant', models.CharField(blank=True, max_length=255, null=True, verbose_name='Quadrant')),
                ('path_row', models.CharField(blank=True, max_length=255, null=True, verbose_name='Path and row')),
                ('areatotalkm', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Total area km')),
                ('areamunkm', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='City area km')),
                ('areauckm', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='UC area km')),
                ('view_date', models.DateField(blank=True, null=True, verbose_name='Visualization data')),
                ('sensor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Optical sensor')),
                ('satellite', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satellite')),
                ('uf', models.CharField(blank=True, max_length=255, null=True, verbose_name='State acronym')),
                ('municipality', models.CharField(blank=True, max_length=255, null=True, verbose_name='City name')),
                ('geocod', models.CharField(blank=True, max_length=255, null=True, verbose_name='Geo code')),
                ('uc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Conservation unit')),
                ('publish_month', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publish month')),
                ('co_cr', models.BigIntegerField(blank=True, null=True, verbose_name='Regional Coordenation code')),
                ('ds_cr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional Coordenation name')),
                ('co_funai', models.IntegerField(blank=True, null=True, verbose_name='Funai code')),
                ('no_ti', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Indigenous Lands')),
                ('nu_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Latitude')),
                ('nu_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Longitude')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Geometry Field')),
            ],
            options={
                'verbose_name': 'Deter Indigenous Lands',
                'verbose_name_plural': 'Deter Indigenous Lands',
                'db_table': 'funai"."lim_deter_a',
                'ordering': ('-view_date', 'no_ti'),
                'managed': False,
            },
        ),
    ]
