# Generated by Django 3.2.3 on 2023-03-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deter_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deterti',
            options={'managed': False, 'ordering': ('-view_date', 'no_ti'), 'verbose_name': 'Deter Indigenous Lands', 'verbose_name_plural': 'Deter Indigenous Lands'},
        ),
    ]
