# Generated by Django 3.2.3 on 2024-03-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deter_monitoring', '0002_alter_deterti_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deterti',
            table='funai"."lim_deter_a',
        ),
    ]
